[tool.poetry]
name = "rescrap"
version = "0.1.2"
description = "Regex Scraper"
authors = ["LouMa <louma.pypi@protonmail.com>"]
keywords = ["scraping", "regex"]
readme = "README.md"
homepage = "https://library.docs.lmdr.xyz/rescrap/"
documentation = "https://library.docs.lmdr.xyz/rescrap/"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.27.1"
PyPDF2 = "^1.26.0"
regex = "^2021.11.10"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.12b0"
mypy = "^0.940"
isort = "^5.10.1"
pre-commit = "^2.18.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
