[tool.poetry]
name = "flowify"
version = "0.1.0"
description = "Interrogate a font file"
authors = ["Simon Cozens <simon@simon-cozens.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.5,<4"
fontfeatures = "*"
inflect = "*"
numpy = "*"
ufoLib2 = "*"
ufo2ft = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
flowify = 'flowify:main'
