[tool.poetry]
name = "briscola-gym"
version = "0.1.0"
description = "Gym environment for Briscola game"
authors = ["Mikedev <mdv1994@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8"
gym = "^0.21.0"
numpy = "^1.21.4"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
