[tool.poetry]
name = "scarfs"
version = "0.1.1"
description = "find approximate fixed points of bounded vector valued functions"
authors = ["Erik Brinkman <erik.brinkman@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.pytest.ini_options]
addopts = "--cov scarfs --cov-report term-missing"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numba = "^0.55.1"
numpy = ">=1.18,<1.22"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
scipy = "^1.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
