# coding: utf-8

"""
    OpenBoxes API specification

    [OpenBoxes](https://openboxes.org) is an open-source LMIS application that increases stock visibility, reduces the risk of stock-outs and stock wastage, and offers tools to improve forecasting and traceability.  **Notice** The following API documentation is a work in progress.  ---   # noqa: E501

    OpenAPI spec version: 0.8.17
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import openboxes
from openboxes.models.tag import Tag  # noqa: E501
from openboxes.rest import ApiException


class TestTag(unittest.TestCase):
    """Tag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTag(self):
        """Test Tag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openboxes.models.tag.Tag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
