[tool.black]
line-length = 95
target-version = ["py35"]

[tool.isort]
profile = "black"
py_version = "35"

[tool.coverage.run]
parallel = false
branch = true
source = ["edc_adherence"]

[tool.coverage.paths]
source = ["edc_adherence", ".tox/*/site-packages"]

[tool.coverage.report]
show_missing = true
skip_covered = true
omit = ["requirements.txt"]
