[tool.poetry]
name = "powershap"
version = "0.0.3"
description = "Feature selection using statistical significance of shap values"
authors = ["Jarne Verhaeghe, Jeroen Van Der Donckt"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/predict-idlab/powershap"
keywords = ["feature selection", "shap", "data-science", "machine learning"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "^1.22.3"
pandas = "^1.4.1"
sklearn = "^0.0"
catboost = "^1.0.5"
statsmodels = "^0.13.2"
shap = "^0.40.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
tensorflow = "^2.8.0"
pyparsing = "2.4.7"
Werkzeug = "2.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
