[tool.poetry]
name = "sparkle-session"
version = "1.3.0"
description = "Common patterns and often used code from dozens of pyspark projects available at your fingertips"
authors = ["Machiel Keizer Groeneveld"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = ">=3.7.1,<4"

[tool.poetry.dev-dependencies]
pyspark = "^3.2.1"
sparkle-test = "^1.2.0"
pytest = "^6.0.2"
flakehell = "^0.6.1"
pytest-parallel = "^0.1.0"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --disable-warnings"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
