[tool.poetry]
name = "pychatz"
version = "1.0.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.22.0"
[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
pychatz = 'package_name:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
