# coding: utf-8

"""
    BAPP API

    This is the primary API for BAPP platform development  # noqa: E501

    OpenAPI spec version: v1
    Contact: office@cbsoft.ro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bapp_api_client
from bapp_api_client.api.cash_register_api import CashRegisterApi  # noqa: E501
from bapp_api_client.rest import ApiException


class TestCashRegisterApi(unittest.TestCase):
    """CashRegisterApi unit test stubs"""

    def setUp(self):
        self.api = bapp_api_client.api.cash_register_api.CashRegisterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cash_register_balance_transfer_create(self):
        """Test case for cash_register_balance_transfer_create

        """
        pass

    def test_cash_register_balance_transfer_delete(self):
        """Test case for cash_register_balance_transfer_delete

        """
        pass

    def test_cash_register_balance_transfer_list(self):
        """Test case for cash_register_balance_transfer_list

        """
        pass

    def test_cash_register_balance_transfer_read(self):
        """Test case for cash_register_balance_transfer_read

        """
        pass

    def test_cash_register_balances_list(self):
        """Test case for cash_register_balances_list

        """
        pass

    def test_cash_register_balances_read(self):
        """Test case for cash_register_balances_read

        """
        pass

    def test_cash_register_bank_deposit_create(self):
        """Test case for cash_register_bank_deposit_create

        """
        pass

    def test_cash_register_bank_deposit_delete(self):
        """Test case for cash_register_bank_deposit_delete

        """
        pass

    def test_cash_register_bank_deposit_list(self):
        """Test case for cash_register_bank_deposit_list

        """
        pass

    def test_cash_register_bank_deposit_partial_update(self):
        """Test case for cash_register_bank_deposit_partial_update

        """
        pass

    def test_cash_register_bank_deposit_read(self):
        """Test case for cash_register_bank_deposit_read

        """
        pass

    def test_cash_register_bank_deposit_update(self):
        """Test case for cash_register_bank_deposit_update

        """
        pass

    def test_cash_register_confirm_transfer_partial_update(self):
        """Test case for cash_register_confirm_transfer_partial_update

        """
        pass

    def test_cash_register_confirm_transfer_update(self):
        """Test case for cash_register_confirm_transfer_update

        """
        pass

    def test_cash_register_location_cashiers_list(self):
        """Test case for cash_register_location_cashiers_list

        """
        pass

    def test_cash_register_location_cashiers_partial_update(self):
        """Test case for cash_register_location_cashiers_partial_update

        """
        pass

    def test_cash_register_location_cashiers_read(self):
        """Test case for cash_register_location_cashiers_read

        """
        pass

    def test_cash_register_location_cashiers_update(self):
        """Test case for cash_register_location_cashiers_update

        """
        pass

    def test_cash_register_movements_list(self):
        """Test case for cash_register_movements_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
