# coding: utf-8

"""
    BAPP API

    This is the primary API for BAPP platform development  # noqa: E501

    OpenAPI spec version: v1
    Contact: office@cbsoft.ro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bapp_api_client
from bapp_api_client.models.company_project_settings import CompanyProjectSettings  # noqa: E501
from bapp_api_client.rest import ApiException


class TestCompanyProjectSettings(unittest.TestCase):
    """CompanyProjectSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompanyProjectSettings(self):
        """Test CompanyProjectSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bapp_api_client.models.company_project_settings.CompanyProjectSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
