# coding: utf-8

"""
    BAPP API

    This is the primary API for BAPP platform development  # noqa: E501

    OpenAPI spec version: v1
    Contact: office@cbsoft.ro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bapp_api_client
from bapp_api_client.api.custom_cargo_api import CustomCargoApi  # noqa: E501
from bapp_api_client.rest import ApiException


class TestCustomCargoApi(unittest.TestCase):
    """CustomCargoApi unit test stubs"""

    def setUp(self):
        self.api = bapp_api_client.api.custom_cargo_api.CustomCargoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_custom_cargo_attachments_create(self):
        """Test case for custom_cargo_attachments_create

        """
        pass

    def test_custom_cargo_attachments_delete(self):
        """Test case for custom_cargo_attachments_delete

        """
        pass

    def test_custom_cargo_attachments_list(self):
        """Test case for custom_cargo_attachments_list

        """
        pass

    def test_custom_cargo_attachments_partial_update(self):
        """Test case for custom_cargo_attachments_partial_update

        """
        pass

    def test_custom_cargo_attachments_read(self):
        """Test case for custom_cargo_attachments_read

        """
        pass

    def test_custom_cargo_attachments_update(self):
        """Test case for custom_cargo_attachments_update

        """
        pass

    def test_custom_cargo_balance_list(self):
        """Test case for custom_cargo_balance_list

        """
        pass

    def test_custom_cargo_balance_partial_update(self):
        """Test case for custom_cargo_balance_partial_update

        """
        pass

    def test_custom_cargo_balance_read(self):
        """Test case for custom_cargo_balance_read

        """
        pass

    def test_custom_cargo_free_days_create(self):
        """Test case for custom_cargo_free_days_create

        """
        pass

    def test_custom_cargo_free_days_delete(self):
        """Test case for custom_cargo_free_days_delete

        """
        pass

    def test_custom_cargo_free_days_list(self):
        """Test case for custom_cargo_free_days_list

        """
        pass

    def test_custom_cargo_free_days_partial_update(self):
        """Test case for custom_cargo_free_days_partial_update

        """
        pass

    def test_custom_cargo_free_days_read(self):
        """Test case for custom_cargo_free_days_read

        """
        pass

    def test_custom_cargo_free_days_update(self):
        """Test case for custom_cargo_free_days_update

        """
        pass

    def test_custom_cargo_records_create(self):
        """Test case for custom_cargo_records_create

        """
        pass

    def test_custom_cargo_records_delete(self):
        """Test case for custom_cargo_records_delete

        """
        pass

    def test_custom_cargo_records_item_create(self):
        """Test case for custom_cargo_records_item_create

        """
        pass

    def test_custom_cargo_records_item_delete(self):
        """Test case for custom_cargo_records_item_delete

        """
        pass

    def test_custom_cargo_records_item_list(self):
        """Test case for custom_cargo_records_item_list

        """
        pass

    def test_custom_cargo_records_item_partial_update(self):
        """Test case for custom_cargo_records_item_partial_update

        """
        pass

    def test_custom_cargo_records_item_read(self):
        """Test case for custom_cargo_records_item_read

        """
        pass

    def test_custom_cargo_records_item_update(self):
        """Test case for custom_cargo_records_item_update

        """
        pass

    def test_custom_cargo_records_list(self):
        """Test case for custom_cargo_records_list

        """
        pass

    def test_custom_cargo_records_partial_update(self):
        """Test case for custom_cargo_records_partial_update

        """
        pass

    def test_custom_cargo_records_read(self):
        """Test case for custom_cargo_records_read

        """
        pass

    def test_custom_cargo_records_update(self):
        """Test case for custom_cargo_records_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
