[tool.poetry]
name = "openly"
version = "0.1.4"
description = ""
authors = ["Josh Brooks <josh@catalpa.io>"]

packages = [
    {include = "aims", from="openly"},
    {include = "dashboard", from="openly"},
    {include = "geodata", from="openly"},
    {include = "iati", from="openly"},
    {include = "gateway", from="openly"},
    {include = "dataquality", from="openly"},
    {include = "editor", from="openly"},
    {include = "activity_list", from="openly"},
    {include = "activity_profile", from="openly"},
    {include = "iati_codelists", from="openly"},
    {include = "iati_compliance", from="openly"},
    {include = "iati_vocabulary", from="openly"},
    {include = "profiles_v2", from="openly"},
    {include = "resources", from="openly"},
    {include = "search", from="openly"},
    {include = "export", from="openly"},
    {include = "oipa", from="openly"},
    {include = "partners", from="openly"},
    {include = "results", from="openly"},
]

[tool.poetry.dependencies]
python = "^3.8"
Django = "<3.2"
djangorestframework = "^3.13.1"
sentry-sdk = "^1.5.8"
celery = "^5.2.3"
django-modeltranslation = "^0.17.5"
django-widget-tweaks = "^1.4.12"
django-crispy-forms = "^1.14.0"
django-registration-redux = "^2.10"
simple-locations = "^3.1.3"
requests = "^2.27.1"
django-model-utils = "^4.2.0"
Pillow = "^9.0.1"
django-geojson = "^3.2.1"
django-el-pagination = "^3.3.0"
django-leaflet = "^0.28.2"
urllib3 = "<1.26"
Whoosh = "^2.7.4"
django-haystack = "^3.1.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
psycopg2-binary = "2.8.4"
playwright = "^1.20.1"
mypy = "^0.942"
pytest-django = "^4.5.2"
factory-boy = "^3.2.1"
pytest-cov = "^3.0.0"
black = "^22.3.0"
responses = "^0.20.0"
flake8 = "^4.0.1"
python-dotenv = "^0.20.0"
django-extensions = "^3.1.5"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
