# configure
image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"  # cache on project level
cache:
  paths:
    - .cache/pip
    - venv/

# common to all scripts
before_script:
  - python -V
  - pip install -U virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -U flit
  - pip install -U pytest
  - pip install -U mypy
  - pip install -U yaqc
  - pip install -U yaqd-core
  - pip install -U yaq-traits
  - pip install -U pyside2
  - FLIT_ROOT_INSTALL=1 flit install

# test stage

# deploy stage
pages:
  stage: deploy
  script:
    - mkdir public
    - cp docs/* public/
  artifacts:
    paths:
    - public/
  only:
  - main
flit:
  stage: deploy
  script:
    - flit publish
  artifacts:
    paths:
      - dist/*
  only:
    - tags
