# coding: utf-8

"""
    BAPP API

    This is the primary API for BAPP platform development  # noqa: E501

    OpenAPI spec version: v1
    Contact: office@cbsoft.ro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bapp_api_client
from bapp_api_client.models.product_type import ProductType  # noqa: E501
from bapp_api_client.rest import ApiException


class TestProductType(unittest.TestCase):
    """ProductType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductType(self):
        """Test ProductType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bapp_api_client.models.product_type.ProductType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
