name: run mypy
on: [push, pull_request]
jobs:
  build:
    name: run mypy
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-pipmypy
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
          ${{ runner.os }}-cache-pip-
    - name: Install deps
      run: pip3 install -U tornado pytest pytest-asyncio pytest-httpbin flaky structlog tomli aiohttp httpx mypy
    - name: Run mypy for --install-types
      run: PATH=$HOME/.local/bin:$PATH mypy nvchecker nvchecker_source tests
      continue-on-error: true
    - name: Install types
      run: PATH=$HOME/.local/bin:$PATH yes | mypy --install-types
    - name: Run mypy
      run: PATH=$HOME/.local/bin:$PATH mypy nvchecker nvchecker_source tests
