name: Ubuntu

on:
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        include:
          # Ubuntu 18.04 + gcc-9
          - name: "Ubuntu 18.04 + gcc-9"
            os: ubuntu-18.04
            compiler: gcc
            version: "9"
          # Ubuntu 20.04 + gcc-10
          - name: "Ubuntu 20.04 + gcc-10"
            os: ubuntu-20.04
            compiler: gcc
            version: "10"
          # Ubuntu 18.04 + clang-9
          - name: "Ubuntu 18.04 + clang-9"
            os: ubuntu-18.04
            compiler: clang
            version: "9"
          # Ubuntu 20.04 + clang-10
          - name: "Ubuntu 20.04 + clang-10"
            os: ubuntu-20.04
            compiler: clang
            version: "10"

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        lfs: true
    - name: Configure Compiler
      run: |
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
        else
          echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
        fi
    - name: Configure Build
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: Build
      run: cd build && make
    - name: Run Unit Test
      run: ./build/test/kiwi-test
    - name: Run Evaluator
      run: |
        mkdir eval_results
        ./build/kiwi-evaluator -m ./ModelGenerator eval_data/*.txt -o eval_results/
    - name: Run Benchmark
      run: |
        curl -OL https://latina.bab2min.pe.kr/_data/kowiki1000.txt
        KIWI_ARCH_TYPE=none ./build/kiwi-cli-* -m ./ModelGenerator -e -o test.out kowiki1000.txt
        KIWI_ARCH_TYPE=balanced ./build/kiwi-cli-* -m ./ModelGenerator -e -o test.out kowiki1000.txt
        KIWI_ARCH_TYPE=sse2 ./build/kiwi-cli-* -m ./ModelGenerator -e -o test.out kowiki1000.txt
        KIWI_ARCH_TYPE=sse4_1 ./build/kiwi-cli-* -m ./ModelGenerator -e -o test.out kowiki1000.txt
        KIWI_ARCH_TYPE=avx2 ./build/kiwi-cli-* -m ./ModelGenerator -e -o test.out kowiki1000.txt
        KIWI_ARCH_TYPE=avx512bw ./build/kiwi-cli-* -m ./ModelGenerator -e -o test.out kowiki1000.txt
    - name: Archive binaries
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts ${{ matrix.name }}
        path: |
          build/*kiwi*
          build/test/*kiwi*
          eval_results/*.txt
