name: Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: rustup update stable
    - uses: Swatinem/rust-cache@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Python dependencies
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Run tests
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install pytest maturin pyarrow
        maturin develop
        PYTHONPATH=. pytest
