[tool.poetry]
name = "rofilde-demo"
version = "0.1.3"
description = ""
authors = ["Rofilde Hasudungan <rofilde@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
readme = "README.md" 
[tool.poetry.dev-dependencies]
pytest = "^5.2"

keywords = ["Rofilde", "Hasudungan"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
