depends = ('ITKPyBase', 'ITKStatistics', 'ITKImageSources', 'ITKFFT', 'ITKCommon', )
templates = (  ('VkComplexToComplex1DFFTImageFilter', 'itk::VkComplexToComplex1DFFTImageFilter', 'itkVkComplexToComplex1DFFTImageFilterICF2', True, 'itk::Image< std::complex< float >,2 >'),
  ('VkComplexToComplex1DFFTImageFilter', 'itk::VkComplexToComplex1DFFTImageFilter', 'itkVkComplexToComplex1DFFTImageFilterICF3', True, 'itk::Image< std::complex< float >,3 >'),
  ('VkComplexToComplex1DFFTImageFilter', 'itk::VkComplexToComplex1DFFTImageFilter', 'itkVkComplexToComplex1DFFTImageFilterICD2', True, 'itk::Image< std::complex< double >,2 >'),
  ('VkComplexToComplex1DFFTImageFilter', 'itk::VkComplexToComplex1DFFTImageFilter', 'itkVkComplexToComplex1DFFTImageFilterICD3', True, 'itk::Image< std::complex< double >,3 >'),
  ('VkComplexToComplexFFTImageFilter', 'itk::VkComplexToComplexFFTImageFilter', 'itkVkComplexToComplexFFTImageFilterICF2', True, 'itk::Image< std::complex< float >,2 >'),
  ('VkComplexToComplexFFTImageFilter', 'itk::VkComplexToComplexFFTImageFilter', 'itkVkComplexToComplexFFTImageFilterICF3', True, 'itk::Image< std::complex< float >,3 >'),
  ('VkComplexToComplexFFTImageFilter', 'itk::VkComplexToComplexFFTImageFilter', 'itkVkComplexToComplexFFTImageFilterICD2', True, 'itk::Image< std::complex< double >,2 >'),
  ('VkComplexToComplexFFTImageFilter', 'itk::VkComplexToComplexFFTImageFilter', 'itkVkComplexToComplexFFTImageFilterICD3', True, 'itk::Image< std::complex< double >,3 >'),
  ('VkForward1DFFTImageFilter', 'itk::VkForward1DFFTImageFilter', 'itkVkForward1DFFTImageFilterIF2', True, 'itk::Image< float,2 >'),
  ('VkForward1DFFTImageFilter', 'itk::VkForward1DFFTImageFilter', 'itkVkForward1DFFTImageFilterIF3', True, 'itk::Image< float,3 >'),
  ('VkForward1DFFTImageFilter', 'itk::VkForward1DFFTImageFilter', 'itkVkForward1DFFTImageFilterID2', True, 'itk::Image< double,2 >'),
  ('VkForward1DFFTImageFilter', 'itk::VkForward1DFFTImageFilter', 'itkVkForward1DFFTImageFilterID3', True, 'itk::Image< double,3 >'),
  ('VkForwardFFTImageFilter', 'itk::VkForwardFFTImageFilter', 'itkVkForwardFFTImageFilterIF2', True, 'itk::Image< float,2 >'),
  ('VkForwardFFTImageFilter', 'itk::VkForwardFFTImageFilter', 'itkVkForwardFFTImageFilterIF3', True, 'itk::Image< float,3 >'),
  ('VkForwardFFTImageFilter', 'itk::VkForwardFFTImageFilter', 'itkVkForwardFFTImageFilterID2', True, 'itk::Image< double,2 >'),
  ('VkForwardFFTImageFilter', 'itk::VkForwardFFTImageFilter', 'itkVkForwardFFTImageFilterID3', True, 'itk::Image< double,3 >'),
  ('VkGlobalConfiguration', 'itk::VkGlobalConfiguration', 'itkVkGlobalConfiguration', True),
  ('VkHalfHermitianToRealInverseFFTImageFilter', 'itk::VkHalfHermitianToRealInverseFFTImageFilter', 'itkVkHalfHermitianToRealInverseFFTImageFilterICF2', True, 'itk::Image< std::complex< float >,2 >'),
  ('VkHalfHermitianToRealInverseFFTImageFilter', 'itk::VkHalfHermitianToRealInverseFFTImageFilter', 'itkVkHalfHermitianToRealInverseFFTImageFilterICF3', True, 'itk::Image< std::complex< float >,3 >'),
  ('VkHalfHermitianToRealInverseFFTImageFilter', 'itk::VkHalfHermitianToRealInverseFFTImageFilter', 'itkVkHalfHermitianToRealInverseFFTImageFilterICD2', True, 'itk::Image< std::complex< double >,2 >'),
  ('VkHalfHermitianToRealInverseFFTImageFilter', 'itk::VkHalfHermitianToRealInverseFFTImageFilter', 'itkVkHalfHermitianToRealInverseFFTImageFilterICD3', True, 'itk::Image< std::complex< double >,3 >'),
  ('VkInverse1DFFTImageFilter', 'itk::VkInverse1DFFTImageFilter', 'itkVkInverse1DFFTImageFilterICF2', True, 'itk::Image< std::complex< float >,2 >'),
  ('VkInverse1DFFTImageFilter', 'itk::VkInverse1DFFTImageFilter', 'itkVkInverse1DFFTImageFilterICF3', True, 'itk::Image< std::complex< float >,3 >'),
  ('VkInverse1DFFTImageFilter', 'itk::VkInverse1DFFTImageFilter', 'itkVkInverse1DFFTImageFilterICD2', True, 'itk::Image< std::complex< double >,2 >'),
  ('VkInverse1DFFTImageFilter', 'itk::VkInverse1DFFTImageFilter', 'itkVkInverse1DFFTImageFilterICD3', True, 'itk::Image< std::complex< double >,3 >'),
  ('VkInverseFFTImageFilter', 'itk::VkInverseFFTImageFilter', 'itkVkInverseFFTImageFilterICF2', True, 'itk::Image< std::complex< float >,2 >'),
  ('VkInverseFFTImageFilter', 'itk::VkInverseFFTImageFilter', 'itkVkInverseFFTImageFilterICF3', True, 'itk::Image< std::complex< float >,3 >'),
  ('VkInverseFFTImageFilter', 'itk::VkInverseFFTImageFilter', 'itkVkInverseFFTImageFilterICD2', True, 'itk::Image< std::complex< double >,2 >'),
  ('VkInverseFFTImageFilter', 'itk::VkInverseFFTImageFilter', 'itkVkInverseFFTImageFilterICD3', True, 'itk::Image< std::complex< double >,3 >'),
  ('VkRealToHalfHermitianForwardFFTImageFilter', 'itk::VkRealToHalfHermitianForwardFFTImageFilter', 'itkVkRealToHalfHermitianForwardFFTImageFilterIF2', True, 'itk::Image< float,2 >'),
  ('VkRealToHalfHermitianForwardFFTImageFilter', 'itk::VkRealToHalfHermitianForwardFFTImageFilter', 'itkVkRealToHalfHermitianForwardFFTImageFilterIF3', True, 'itk::Image< float,3 >'),
  ('VkRealToHalfHermitianForwardFFTImageFilter', 'itk::VkRealToHalfHermitianForwardFFTImageFilter', 'itkVkRealToHalfHermitianForwardFFTImageFilterID2', True, 'itk::Image< double,2 >'),
  ('VkRealToHalfHermitianForwardFFTImageFilter', 'itk::VkRealToHalfHermitianForwardFFTImageFilter', 'itkVkRealToHalfHermitianForwardFFTImageFilterID3', True, 'itk::Image< double,3 >'),
)
factories = ()
