[tool.poetry]
name = "materia-structure"
version = "1.1.0"
description = "Streamlined interface for managing atomistic structure data."
authors = ["Ki-Jana Carter <kijana@mit.edu>"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/kijanac/materia-structure"
homepage = "https://github.com/kijanac/materia-structure"
packages = [
    { include = "materia", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.21.1"
scipy = "^1.7.3"
PubChemPy = "^1.0.4"
unyt = "^2.8.0"
materia-utils = "^1.0.0"

[tool.poetry2conda.dependencies.openbabel]
name = "openbabel"
channel = "conda-forge"
version = "^v3.1.1"

[tool.manage.conda-dependencies.openbabel]
git = "https://github.com/openbabel/openbabel.git"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
poetry2conda = "^0.3.0"
"ruamel.yaml" = "^0.16.12"
toml = "^0.10.2"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
sphinx-rtd-theme = "^0.5.1"
sphinx-autodoc-typehints = "^1.16.0"
sphinx-jinja = "^1.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry2conda]
name = "materia-structure"

[tool.pytest.ini_options]
minversion = 6.0
addopts = "-x -v --cov --cov-report=xml"
testpaths = "tests"
