# coding: utf-8

"""
    BAPP API

    This is the primary API for BAPP platform development  # noqa: E501

    OpenAPI spec version: v1
    Contact: office@cbsoft.ro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bapp_api_client.configuration import Configuration


class DocSiteCategory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'domain': 'int',
        'name': 'str',
        'slug': 'str',
        'extra': 'object',
        'parent': 'int',
        'description': 'str',
        'seo_title': 'str',
        'seo_description': 'str',
        'seo_keywords': 'str'
    }

    attribute_map = {
        'id': 'id',
        'domain': 'domain',
        'name': 'name',
        'slug': 'slug',
        'extra': 'extra',
        'parent': 'parent',
        'description': 'description',
        'seo_title': 'seo_title',
        'seo_description': 'seo_description',
        'seo_keywords': 'seo_keywords'
    }

    def __init__(self, id=None, domain=None, name=None, slug=None, extra=None, parent=None, description=None, seo_title=None, seo_description=None, seo_keywords=None, _configuration=None):  # noqa: E501
        """DocSiteCategory - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._domain = None
        self._name = None
        self._slug = None
        self._extra = None
        self._parent = None
        self._description = None
        self._seo_title = None
        self._seo_description = None
        self._seo_keywords = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if domain is not None:
            self.domain = domain
        self.name = name
        if slug is not None:
            self.slug = slug
        if extra is not None:
            self.extra = extra
        if parent is not None:
            self.parent = parent
        if description is not None:
            self.description = description
        if seo_title is not None:
            self.seo_title = seo_title
        if seo_description is not None:
            self.seo_description = seo_description
        if seo_keywords is not None:
            self.seo_keywords = seo_keywords

    @property
    def id(self):
        """Gets the id of this DocSiteCategory.  # noqa: E501


        :return: The id of this DocSiteCategory.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DocSiteCategory.


        :param id: The id of this DocSiteCategory.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def domain(self):
        """Gets the domain of this DocSiteCategory.  # noqa: E501


        :return: The domain of this DocSiteCategory.  # noqa: E501
        :rtype: int
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this DocSiteCategory.


        :param domain: The domain of this DocSiteCategory.  # noqa: E501
        :type: int
        """

        self._domain = domain

    @property
    def name(self):
        """Gets the name of this DocSiteCategory.  # noqa: E501


        :return: The name of this DocSiteCategory.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DocSiteCategory.


        :param name: The name of this DocSiteCategory.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name is not None and len(name) > 200):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `200`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def slug(self):
        """Gets the slug of this DocSiteCategory.  # noqa: E501


        :return: The slug of this DocSiteCategory.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this DocSiteCategory.


        :param slug: The slug of this DocSiteCategory.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                slug is not None and len(slug) < 1):
            raise ValueError("Invalid value for `slug`, length must be greater than or equal to `1`")  # noqa: E501

        self._slug = slug

    @property
    def extra(self):
        """Gets the extra of this DocSiteCategory.  # noqa: E501


        :return: The extra of this DocSiteCategory.  # noqa: E501
        :rtype: object
        """
        return self._extra

    @extra.setter
    def extra(self, extra):
        """Sets the extra of this DocSiteCategory.


        :param extra: The extra of this DocSiteCategory.  # noqa: E501
        :type: object
        """

        self._extra = extra

    @property
    def parent(self):
        """Gets the parent of this DocSiteCategory.  # noqa: E501


        :return: The parent of this DocSiteCategory.  # noqa: E501
        :rtype: int
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this DocSiteCategory.


        :param parent: The parent of this DocSiteCategory.  # noqa: E501
        :type: int
        """

        self._parent = parent

    @property
    def description(self):
        """Gets the description of this DocSiteCategory.  # noqa: E501


        :return: The description of this DocSiteCategory.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this DocSiteCategory.


        :param description: The description of this DocSiteCategory.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def seo_title(self):
        """Gets the seo_title of this DocSiteCategory.  # noqa: E501


        :return: The seo_title of this DocSiteCategory.  # noqa: E501
        :rtype: str
        """
        return self._seo_title

    @seo_title.setter
    def seo_title(self, seo_title):
        """Sets the seo_title of this DocSiteCategory.


        :param seo_title: The seo_title of this DocSiteCategory.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                seo_title is not None and len(seo_title) > 200):
            raise ValueError("Invalid value for `seo_title`, length must be less than or equal to `200`")  # noqa: E501

        self._seo_title = seo_title

    @property
    def seo_description(self):
        """Gets the seo_description of this DocSiteCategory.  # noqa: E501


        :return: The seo_description of this DocSiteCategory.  # noqa: E501
        :rtype: str
        """
        return self._seo_description

    @seo_description.setter
    def seo_description(self, seo_description):
        """Sets the seo_description of this DocSiteCategory.


        :param seo_description: The seo_description of this DocSiteCategory.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                seo_description is not None and len(seo_description) > 200):
            raise ValueError("Invalid value for `seo_description`, length must be less than or equal to `200`")  # noqa: E501

        self._seo_description = seo_description

    @property
    def seo_keywords(self):
        """Gets the seo_keywords of this DocSiteCategory.  # noqa: E501


        :return: The seo_keywords of this DocSiteCategory.  # noqa: E501
        :rtype: str
        """
        return self._seo_keywords

    @seo_keywords.setter
    def seo_keywords(self, seo_keywords):
        """Sets the seo_keywords of this DocSiteCategory.


        :param seo_keywords: The seo_keywords of this DocSiteCategory.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                seo_keywords is not None and len(seo_keywords) > 200):
            raise ValueError("Invalid value for `seo_keywords`, length must be less than or equal to `200`")  # noqa: E501

        self._seo_keywords = seo_keywords

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocSiteCategory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocSiteCategory):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DocSiteCategory):
            return True

        return self.to_dict() != other.to_dict()
