# coding: utf-8

"""
    BAPP API

    This is the primary API for BAPP platform development  # noqa: E501

    OpenAPI spec version: v1
    Contact: office@cbsoft.ro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bapp_api_client.configuration import Configuration


class ProjectTemplate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'lists': 'int',
        'tasks': 'int'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'lists': 'lists',
        'tasks': 'tasks'
    }

    def __init__(self, id=None, name=None, lists=None, tasks=None, _configuration=None):  # noqa: E501
        """ProjectTemplate - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._name = None
        self._lists = None
        self._tasks = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        if lists is not None:
            self.lists = lists
        if tasks is not None:
            self.tasks = tasks

    @property
    def id(self):
        """Gets the id of this ProjectTemplate.  # noqa: E501


        :return: The id of this ProjectTemplate.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProjectTemplate.


        :param id: The id of this ProjectTemplate.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ProjectTemplate.  # noqa: E501


        :return: The name of this ProjectTemplate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProjectTemplate.


        :param name: The name of this ProjectTemplate.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name is not None and len(name) > 100):
            raise ValueError("Invalid value for `name`, length must be less than or equal to `100`")  # noqa: E501
        if (self._configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def lists(self):
        """Gets the lists of this ProjectTemplate.  # noqa: E501

        Number of lists  # noqa: E501

        :return: The lists of this ProjectTemplate.  # noqa: E501
        :rtype: int
        """
        return self._lists

    @lists.setter
    def lists(self, lists):
        """Sets the lists of this ProjectTemplate.

        Number of lists  # noqa: E501

        :param lists: The lists of this ProjectTemplate.  # noqa: E501
        :type: int
        """

        self._lists = lists

    @property
    def tasks(self):
        """Gets the tasks of this ProjectTemplate.  # noqa: E501

        Number of tasks  # noqa: E501

        :return: The tasks of this ProjectTemplate.  # noqa: E501
        :rtype: int
        """
        return self._tasks

    @tasks.setter
    def tasks(self, tasks):
        """Sets the tasks of this ProjectTemplate.

        Number of tasks  # noqa: E501

        :param tasks: The tasks of this ProjectTemplate.  # noqa: E501
        :type: int
        """

        self._tasks = tasks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectTemplate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectTemplate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectTemplate):
            return True

        return self.to_dict() != other.to_dict()
