# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-17 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import profiles_v2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iati', '0006_auto_20160923_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('background', models.TextField(blank=True, max_length=10000, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profiles/organisation_logo/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='profiles/organisation_banner_image/')),
                ('banner_text', models.CharField(blank=True, max_length=256, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='iati.Organisation')),
            ],
            bases=(models.Model, profiles_v2.models.ImageModel),
        ),
    ]
