# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-13 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_v2', '0003_person'),
        ('profiles_v2', '0003_auto_20161206_1357'),
    ]

    operations = [
    ]
