# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-07 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_v2', '0005_auto_20161213_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationcontactinfo',
            name='facebook',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
