[tool.poetry]
name = "CS_Money_Parser"
version = "0.0.3"
description = "Quick programmatic search for objects from the site cs.money"
authors = ["Dark Laybel"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
