[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "todoist_helper"
authors = [{name = "0x29a", email = "nk0d6bxt@anonaddy.me"}]
license = {file = "LICENSE"}
readme = "README.md"
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
dynamic = ["version", "description"]
requires-python = ">=3.8"
dependencies = [
  "click==8.0.3",
  "todoist-python==8.1.3",
]

[project.urls]
Home = "https://github.com/0x29a/todoist_helper"

[project.scripts]
todoist_helper = "todoist_helper.main:cli"
