name: libimpel meson CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-disto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/meson-build@v1.0.3
        with:
          #setup-options: --werror
          options: --verbose
          action: test
      # Preserve meson's log file on failure
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Linux_Meson_Testlog
          path: build/meson-logs/testlog.txt
