[tool.poetry]
name = "devind_notifications"
version = "0.4.2"
description = "Devind django app for notifications."
authors = ["Victor <lyferov@yandex.ru>"]
license = "MIT"
homepage = "https://github.com/devind-team/devind-django-notifications"
repository = "https://github.com/devind-team/devind-django-notifications"
keywords = ["django", "graphene", "notifications"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Framework :: Django"
]

[tool.poetry.dependencies]
python = "^3.9"
devind-core = "^0"
Django = "^3"
graphene-django = "^2.15.0"
devind-helpers = "^0"
celery = "^5.2.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "devind_notifications/__init__.py:__version__",
    "pyproject.toml:version"
]
branch = "main"
upload_to_pypi = true
upload_to_release = true
build_command = "pip install poetry && poetry build"
