
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-11T11:00:07-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd5d06e5aa5736da30151690a530ca7766c05609",
 "version": "v2.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
