title = "NEAT input parameters"
 
[equilibrium]
stel = 'Qsc.from_paper(1,nphi=151,B0=3)'
name = 'paper_r2_5.1'
r0     = 0.12
Lambda = [0.99]
B20real = false
 
[folders]
results_folder = 'results'
 
[particles]
theta0   = [3.14]
phi0     = [0.01]
charge   = 1
rhom     = 1
mass     = 1
energy   = [4e4]
nsamples = 500
Tfinal   = 1500

[plotting]
makePlots = 1
showPlots = 0
Animation = 0
SaveMovie = 0
nstep  = 1 # step size in the time series for the particle orbit (step=1 show all time steps)
ncores = 6 # number of cores used in the parallelization to unpack orbit position(t)
ntheta = 30 # poloidal resolution for the 3D plot
# nphi   = 60 # ##CLASH WITH PREVOUS nph #toroidal resolution for the 3D plot
boundaryR0 = 0.09
savePlots = 1
