[tool.poetry]
name = "pyserde"
version = "0.7.2"
description = "Yet another serialization library on top of dataclasses"
authors = ["yukinarit <yukinarit84@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/yukinarit/pyserde"
homepage = "https://github.com/yukinarit/pyserde"
packages = [
    { include = "serde" },
]
classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: Implementation :: CPython",
		"Programming Language :: Python :: Implementation :: PyPy",
    ]

[tool.poetry.dependencies]
python = "^3.7.0"
typing_inspect = ">=0.4.0"
stringcase = "*"
jinja2 = "*"
msgpack = { version = "*", markers = "extra == 'msgpack' or extra == 'all'", optional = true }
toml = { version = "*", markers = "extra == 'toml' or extra == 'all'", optional = true }
pyyaml = { version = "*", markers = "extra == 'yaml' or extra == 'all'", optional = true }

[tool.poetry.dev-dependencies]
pyyaml = "*"
toml = "*"
msgpack = "*"
flake8 = "*"
pytest = "*"
pytest-cov = "*"
pytest-watch = "*"
pytest-flake8 = "*"
coverage = "==4.5.4"
pdoc = { version = "~=8" }
mypy = { version = "==0.931", markers = "platform_python_implementation!='PyPy'" }
more-itertools = "~=8.6.0"
pre-commit = "==v2.10.1"
pytest-xdist = "^2.3.0"

[tool.poetry.extras]
msgpack = ["msgpack"]
toml = ["toml"]
yaml = ["pyyaml"]
all = ["msgpack", "toml", "pyyaml"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
