[tool.poetry]
name = "barstow"
version = "0.1.3"
description = "Library for managing Arrow datasets"
authors = ["Mat Leonard <leonard.mat@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pyarrow = "^7.0.0"
pandas = "^1.4.1"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
mypy = "^0.940"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"