
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-13T16:52:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7f78e34adbe84087c16aa1cf0a6ed114b9a9e89",
 "version": "6.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
