# coding: utf-8

"""
    BAPP API

    This is the primary API for BAPP platform development  # noqa: E501

    OpenAPI spec version: v1
    Contact: office@cbsoft.ro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bapp_api_client.configuration import Configuration


class WorkflowStep(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'step': 'int',
        'position': 'int',
        'read_only': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'step': 'step',
        'position': 'position',
        'read_only': 'read_only'
    }

    def __init__(self, id=None, step=None, position=None, read_only=None, _configuration=None):  # noqa: E501
        """WorkflowStep - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._step = None
        self._position = None
        self._read_only = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.step = step
        if position is not None:
            self.position = position
        if read_only is not None:
            self.read_only = read_only

    @property
    def id(self):
        """Gets the id of this WorkflowStep.  # noqa: E501


        :return: The id of this WorkflowStep.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WorkflowStep.


        :param id: The id of this WorkflowStep.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def step(self):
        """Gets the step of this WorkflowStep.  # noqa: E501


        :return: The step of this WorkflowStep.  # noqa: E501
        :rtype: int
        """
        return self._step

    @step.setter
    def step(self, step):
        """Sets the step of this WorkflowStep.


        :param step: The step of this WorkflowStep.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and step is None:
            raise ValueError("Invalid value for `step`, must not be `None`")  # noqa: E501

        self._step = step

    @property
    def position(self):
        """Gets the position of this WorkflowStep.  # noqa: E501


        :return: The position of this WorkflowStep.  # noqa: E501
        :rtype: int
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this WorkflowStep.


        :param position: The position of this WorkflowStep.  # noqa: E501
        :type: int
        """

        self._position = position

    @property
    def read_only(self):
        """Gets the read_only of this WorkflowStep.  # noqa: E501


        :return: The read_only of this WorkflowStep.  # noqa: E501
        :rtype: bool
        """
        return self._read_only

    @read_only.setter
    def read_only(self, read_only):
        """Sets the read_only of this WorkflowStep.


        :param read_only: The read_only of this WorkflowStep.  # noqa: E501
        :type: bool
        """

        self._read_only = read_only

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkflowStep, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkflowStep):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WorkflowStep):
            return True

        return self.to_dict() != other.to_dict()
