id: deployment-legacy-deploy
type: service
version: 1.0.0
tasks:
  - id: start
    driver: print
    provides:
      - deployment-legacy-deploy.start
    requires:
      - deployment-state.legacy-deploy-start
    message: "DEPLOYMENT: Legacy Deployment start"

  - id: deployment
    driver: ansible_runner
    provides:
      - deployment-legacy-deploy.deployment
    requires:
      - deployment-legacy-deploy.start
    playbook: deploy_steps_external_deployment_playbook.yaml
    runner_options:
      extravars: global_vars.yaml

  - id: end
    driver: print
    provides:
      - deployment-legacy-deploy.end
    requires:
      - deployment-legacy-deploy.deployment
    needed-by:
      - deployment-state.legacy-deploy-end
    message: "DEPLOYMENT: Legacy Deployment end"
