id: deployment-post-deploy
type: service
version: 1.0.0
tasks:
  - id: start
    driver: print
    provides:
      - deployment-post-deploy.start
    requires:
      - deployment-state.post-deploy-start
    message: "DEPLOYMENT: post deploy start"

  - id: deployment
    driver: ansible_runner
    provides:
      - deployment-post-deploy.deployment
    requires:
      - deployment-post-deploy.start
    playbook: deploy_steps_post_deployment_playbook.yaml
    runner_options:
      extravars: global_vars.yaml

  - id: tasks
    driver: ansible_runner
    provides:
      - deployment-post-deploy.tasks
    requires:
      - deployment-post-deploy.deployment
    playbook: deploy_steps_post_deploy_tasks_playbook.yaml
    runner_options:
      extravars: global_vars.yaml

  - id: end
    driver: print
    provides:
      - deployment-post-deploy.end
    requires:
      - deployment-post-deploy.tasks
    needed-by:
      - deployment-state.post-deploy-end
    message: "DEPLOYMENT: post deploy start"

