id: deployment-host-prep
type: service
version: 1.0.0
tasks:
  - id: start
    driver: print
    provides:
      - deployment-host-prep.start
    requires:
      - deployment-state.host-prep-start
    message: "DEPLOYMENT: host prep start"

  - id: pre-deployment
    driver: ansible_runner
    provides:
      - deployment-host-prep.pre-deployment
    requires:
      - deployment-host-prep.start
    playbook: deploy_steps_pre_deployment_playbook.yaml
    runner_options:
      extravars: global_vars.yaml

  - id: host-prep
    driver: ansible_runner
    provides:
      - deployment-host-prep.host-prep
    requires:
      - deployment-host-prep.pre-deployment
    playbook: deploy_steps_host_prep_playbook.yaml
    runner_options:
      extravars: global_vars.yaml

  - id: container-setup
    driver: ansible_runner
    provides:
      - deployment-host-prep.container-setup
    requires:
      - deployment-host-prep.host-prep
    playbook: deploy_steps_container_setup_tasks_playbook.yaml
    runner_options:
      extravars: global_vars.yaml

  - id: end
    driver: print
    provides:
      - deployment-host-prep.end
    requires:
      - deployment-host-prep.container-setup
    needed-by:
      - deployment-state.host-prep-end
    message: "DEPLOYMENT: host prep end"

