id: deployment-network
type: service
version: 1.0.0
tasks:
  - id: start
    driver: print
    provides:
      - deployment-network.start
    requires:
      - deployment-state.network-start
    message: "DEPLOYMENT: network configuration start"

  - id: network-deployment
    driver: ansible_runner
    provides:
      - deployment-network.deployment
    requires:
      - deployment-network.start
    playbook: deploy_steps_network_deployments_playbook.yaml
    runner_options:
      extravars: global_vars.yaml

  - id: network-validation
    driver: ansible_runner
    provides:
      - deployment-network.validation
    requires:
      - deployment-network.deployment
    playbook: deploy_steps_network_validation_playbook.yaml
    runner_options:
      extravars: global_vars.yaml

  - id: end
    driver: print
    provides:
      - deployment-network.end
    requires:
      - deployment-network.validation
    needed-by:
      - deployment-state.network-end
    message: "DEPLOYMENT: network configuration"
