[UnnecessaryElif]
markup = 'markdown'
content = '''
Looks like you have an unnecessary Elif condition.
It might be better in this case to just use an Else.
For example, instead of:
```python
if x < 5:
    # do something
elif x >= 5:
    # do something else
```
Consider doing this:
```python
if x < 5:
    # do something
else:
    # do something else
```

Or, instead of:
```python
if current is None:
    current = Node()
elif current is not None:
    current = current.next
```
Consider doing this:
```python
if current is None:
    current = Node()
else:
    current = current.next
```
'''

[IfElseReturnBool]
markup = 'markdown'
content = '''
Looks like you are returning two booleans inside of an If/Else statement.
It might be better if you just return the If condition or its inverse.
For example, instead of:
```python
if x < 5:
    return True
else:
    return False
```
Consider doing this:
```python
return x < 5
```

Or, instead of:
```python
if x % 2 == 0:
    return False
else:
    Return True
```
Consider doing this:
```python
return x % 2 == 1
```
'''

[IfReturnBool]
markup = 'markdown'
content = '''
Looks like you are returning the result of some conditional check with
boolean literals.
It might be better in this case to just return the condition itself.
For example, instead of:
```python
if x < 5:
    return True
return False
```
Consider doing this:
```python
return x < 5
```

Or, instead of:
```python
if x % 2 == 0:
    return False
return True
```
Consider doing:
```python
return x % 2 == 1
'''

[IfElseAssignReturn]
markup = 'markdown'
content = ''''''  # ToDo - Add Description

[IfElseAssignBoolReturn]
markup = 'markdown'
content = ''''''  # ToDo - Add Description

[IfElseAssignBool]
markup = 'markdown'
content = ''''''  # ToDo - Add Description

[EmptyIfBody]
markup = 'markdown'
content = ''''''  # ToDo - Add Description

[EmptyElseBody]
markup = 'markdown'
content = ''''''  # ToDo - Add Description

[NestedIf]
markup = 'markdown'
content = ''''''  # ToDo - Add Description

[ConfusingElse]
markup = 'markdown'
content = ''''''  # ToDo - Add Description

[UnnecessaryElse]
markup = 'markdown'
content = ''''''  # ToDo - Add Description

[DuplicateIfElseStatement]
markup = 'markdown'
content = ''''''  # ToDo - Add Description

[SeveralDuplicateIfElseStatements]
markup = 'markdown'
content = ''''''  # ToDo - Add Description

[DuplicateIfElseBody]
markup = 'markdown'
content = ''''''  # ToDo - Add Description

[DeclarationAssignmentDivision]
markup = 'markdown'
content = ''''''  # ToDo - Add Description
