[tool.poetry]
name = "tulpar"
version = "0.0.3"
description = "A Python SSR Framework built on Falcon, PonyORM, and HTMX"
authors = ["Ian Kollipara <ian.kollipara@cune.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
falcon = "^3.1.0"
pony = "^0.7.16"
Jinja2 = "^3.1.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
radon = "^5.1.0"
bandit = "^1.7.4"
pylint = "^2.13.4"
black = "^22.3.0"
isort = "^5.10.1"
coverage = "^6.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
