[tool.poetry]
name = "blackblox"
version = "0.3"
description = "Simple simulator for black box process models"
authors = ["S.E. Tanzer <S.E.Tanzer@tudelft.nl>", "João Paulo Pizani <J.P.PizaniFlor@tudelft.nl>"]
license = "GPL-3.0-only"

readme = "README.md"
homepage = "https://concoctions.org/blackblox/"
repository = "https://github.com/concoctions/BlackBlox"


[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.20"
graphviz = "^0.16"
molmass = "^2020.6.10"
matplotlib = "^3.4"
pandas = "1.3.5"
xlrd = "^2.0.1"
openpyxl = "^3.0.7"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
sphinx = "^4.3.1"
myst_parser = "^0.15.2"
sphinx-rtd-theme = "^1.0.0"
sphinx-markdown-tables = "^0.0.15"
mock = "^4.0.3"


[tool.poetry.scripts]
blackblox = 'blackblox.cli_app:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"