[tool.black]
line-length = 120
target-version = ["py310"]

[tool.setuptools_scm]
write_to = "pycnnum/_version.py"

[tool.pytest.ini_options]
# --cov-append for doctest-modules to work with pytest-cov
addopts = "--doctest-modules -q --cov=pycnnum --cov-report xml:cov.xml --cov-append"
testpaths = [
    "pycnnum",
    "tests"
]

[project]
name = "pycnnum"
authors = [
    {name = "Shuo Li", email = "zeicold@qq.com"},
]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.10"
dynamic = ["version", "description"]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest >= 7.1.1",
    "pytest-cov >= 3.0.0",
    "pytest-xdist >= 2.5.0",
    "pdoc >= 10.0.4",
    "pylint",
    "mypy",
    "flit >= 3.7.1",
    "pre-commit >= 2.18.1"
]

[project.urls]
# Documentation = "https://flit.readthedocs.io/en/latest/"
Source = "https://gitee.com/zeicold/pycnnum"

[build-system]
requires = ["flit_core >=3.4,<4",
    "setuptools>=45", # for setuptool_scm
    "setuptools_scm[toml]>=6.2"
]
build-backend = "flit_core.buildapi"
