[tool.poetry]
name = "csrspy"
version = "0.2.3"
description = ""
authors = ["Taylor Denouden <taylordenouden@gmail.com>"]
packages = [
    { include = "csrspy" }
]
[tool.poetry.dependencies]
python = "^3.8"
pyproj = "^3.3.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
tox = "^3.24.5"
coverage = "^6.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
