
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-08T13:33:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "37ea6b6c0d87ff9092fd0fd04610f5ea8683af74",
 "version": "2022.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
