# coding: utf-8

"""
    BAPP API

    This is the primary API for BAPP platform development  # noqa: E501

    OpenAPI spec version: v1
    Contact: office@cbsoft.ro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bapp_api_client
from bapp_api_client.models.inline_response200149 import InlineResponse200149  # noqa: E501
from bapp_api_client.rest import ApiException


class TestInlineResponse200149(unittest.TestCase):
    """InlineResponse200149 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200149(self):
        """Test InlineResponse200149"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bapp_api_client.models.inline_response200149.InlineResponse200149()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
