# coding: utf-8

"""
    BAPP API

    This is the primary API for BAPP platform development  # noqa: E501

    OpenAPI spec version: v1
    Contact: office@cbsoft.ro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bapp_api_client
from bapp_api_client.api.online_payment_api import OnlinePaymentApi  # noqa: E501
from bapp_api_client.rest import ApiException


class TestOnlinePaymentApi(unittest.TestCase):
    """OnlinePaymentApi unit test stubs"""

    def setUp(self):
        self.api = bapp_api_client.api.online_payment_api.OnlinePaymentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_online_payment_config_list(self):
        """Test case for online_payment_config_list

        """
        pass

    def test_online_payment_config_partial_update(self):
        """Test case for online_payment_config_partial_update

        """
        pass

    def test_online_payment_config_read(self):
        """Test case for online_payment_config_read

        """
        pass

    def test_online_payment_config_stripe_partial_update(self):
        """Test case for online_payment_config_stripe_partial_update

        """
        pass

    def test_online_payment_config_stripe_read(self):
        """Test case for online_payment_config_stripe_read

        """
        pass

    def test_online_payment_config_stripe_update(self):
        """Test case for online_payment_config_stripe_update

        """
        pass

    def test_online_payment_config_update(self):
        """Test case for online_payment_config_update

        """
        pass

    def test_online_payment_link_read(self):
        """Test case for online_payment_link_read

        """
        pass

    def test_online_payment_providers_list(self):
        """Test case for online_payment_providers_list

        """
        pass

    def test_online_payment_stripe_saved_cards_create(self):
        """Test case for online_payment_stripe_saved_cards_create

        """
        pass

    def test_online_payment_stripe_saved_cards_delete(self):
        """Test case for online_payment_stripe_saved_cards_delete

        """
        pass

    def test_online_payment_stripe_saved_cards_list(self):
        """Test case for online_payment_stripe_saved_cards_list

        """
        pass

    def test_online_payment_stripe_saved_cards_partial_update(self):
        """Test case for online_payment_stripe_saved_cards_partial_update

        """
        pass

    def test_online_payment_stripe_saved_cards_read(self):
        """Test case for online_payment_stripe_saved_cards_read

        """
        pass

    def test_online_payment_stripe_saved_cards_update(self):
        """Test case for online_payment_stripe_saved_cards_update

        """
        pass

    def test_online_payment_transaction_create(self):
        """Test case for online_payment_transaction_create

        """
        pass

    def test_online_payment_transaction_get_result(self):
        """Test case for online_payment_transaction_get_result

        """
        pass

    def test_online_payment_transaction_list(self):
        """Test case for online_payment_transaction_list

        """
        pass

    def test_online_payment_transaction_partial_update(self):
        """Test case for online_payment_transaction_partial_update

        """
        pass

    def test_online_payment_transaction_read(self):
        """Test case for online_payment_transaction_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
