# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-08 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0013_auto_20170511_1604'),
        ('aims', '0032_aidtype_move_newmodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidtype',
            name='category',
        ),
        migrations.AlterField(
            model_name='activity',
            name='default_aid_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aims.AidType'),
        ),
        migrations.AlterField(
            model_name='crsadd',
            name='aid_type_flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aims.AidTypeFlag'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='aid_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aims.AidType'),
        ),
        migrations.DeleteModel(
            name='AidType',
        ),
        migrations.DeleteModel(
            name='AidTypeCategory',
        ),
        migrations.DeleteModel(
            name='AidTypeFlag',
        ),
    ]
