[tool.poetry]
name = "uganda-uber-switching-reg"
version = "0.2.0"
description = "A robust estimator to machine learning prediction misclassification"
authors = ["Aleksandr Michuda <amichuda@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
matplotlib = "3.4.3"
numpy = "1.20.3"
linearmodels = "4.24"
patsy = "0.5.2"
scipy = "1.7.1"
statsmodels = "0.12.2"
pandas = "1.3.2"
tqdm = "4.56.0"
scikit-learn = "0.24.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0",  "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
metadata = true
dirty = true
style = "semver"