VERSION_YEAR = 2022
VERSION_MONTH = int('04')
VERSION_DAY = int('13')
VERSION_HOUR = int('03')
VERSION_MINUTE = int('05')
MAJOR_VERSION = 1
MINOR_VERSION = 3
PATCH_VERSION = 202204130305
version_date = '2022/04/13 03:05'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
