name: readthedocs
dependencies:
  - python=3.9
  - conda-forge::gfortran=11.2.0
  - numpy>=1.22.2
  - scipy>=1.7.3
  - matplotlib>=3.5.0
  - pip>=21.2.4
  - pip:
    - sphinx-book-theme==0.2.0
    - sphinx-panels==0.6.0
    - nbsphinx==0.8.8
    - sphinx-togglebutton==0.3.0
