from ..core import Storage

class MegaCloudStorage(Storage):
    def __init__(self, email, password, root: str = ..., **kwargs) -> None: ...
    def exists(self, key: str) -> bool: ...
    def save(self, key: str, data: bytes) -> None: ...
    def load(self, key: str) -> bytes: ...
    def delete(self, key: str): ...
