
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-02T18:16:17+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8dca795bf27699bb5e6623775d730b3d5f62bee7",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
