[tool.poetry]
name = "pyscaffold-interactive"
version = "0.3.0"
description = "Interactive PyScaffold - An interactive Python project template generator based on PyScaffold"
authors = ["Sarthak Jariwala"]
license = "MIT"
readme = "README.rst"

[tool.poetry.scripts]
putup-interactive = "pyscaffold_interactive.cli:run"

[tool.poetry.dependencies]
python = "^3.7"
PyScaffold = {extras = ["all"], version = "^4.2.1"}
click = "^8.1.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
nox = "^2022.1.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
