[tool.poetry]
name = "apollo-lunar"
version = "2022.4.11rc1"
description = "A Python SDK/CLI for Lunar API"
authors = ["Lunar module <lunar@sktio.io>"]
readme = "README.md"
license = "MIT"
include = [
    "LICENSE",
]
packages = [
    { include = "lunar" },
    { include = "bap" }
]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.1"
requests = "^2.25.1"
pydantic = "^1.8.2"
aiohttp = "^3.7.4"
scikit-learn = {version = "~1.0.2", optional = true}
catboost = {version = "~1.0.4", optional = true}
lightgbm = {version = "~3.3.2", optional = true}
xgboost = {version = "~1.5.2", optional = true}
boto3 = "*"
cloudpickle = "^1.6.0"

[tool.poetry.extras]
ml = ["scikit-learn", "catboost", "lightgbm", "xgboost"]

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^3.9.2"
pytest = "^6.2.4"
pytest-mock = "^3.6.1"
pdoc3 = "^0.9.2"
jupyterlab = "^3.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
lunar = "lunar.cli:main"
