[tool.poetry]
name = "ulidgen"
version = "0.1.0"
description = "CLI tool to generate ULID strings"
authors = ["Enam Mijbah Noor <enammijbahnoor@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
ulidgen = "ulidgen.cli:main"

[tool.poetry.dependencies]
python = "^3.5"
ulid-py = "^1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
