name: geosnap
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - giddy >=2.2.1
  - libpysal
  - cenpy
  - geopandas
  - matplotlib
  - scikit-learn
  - seaborn
  - pyarrow >=0.14.1
  - appdirs
  - dash
  - dash-bootstrap-components
  - palettable
  - pip
  - tqdm
  - quilt3 >=3.6
  - xlrd
  - tobler >=0.8.2
  - proplot >=0.9
  - contextily
  - scikit-plot
  - mapclassify
  - spopt >=0.1.1
  - s3fs
  - segregation >=2.0
  - versioneer

  