
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-02-08T14:32:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f982cce12a15afaecd1f320493c7b86338ad1c6",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
