[tool.poetry]
name = "chilitools"
version = "0.1.1"
description = "Tools for CHILI Publish"
authors = ["Austin Meier <austin.meier@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.27.1"
xmltodict = "^0.12.0"
img2pdf = "^0.4.4"
Pillow = "^9.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
