[tool.poetry]
name = "async-ipython"
version = "0.0.3"
description = "An enhanced async interactive python."
authors = ["Alex Hutz <frostiiweeb@gmail.com>"]
license = "MPL-2.0"
readme = 'README.md'
homepage = "https://github.com/FrostiiWeeb/aipython"
repository = "https://github.com/FrostiiWeeb/aipython"
keywords = ['interactive', 'console', 'python']
build = "build.py"

packages = [
   { include = "aipython", format = ["sdist", "wheel"]}
]

[tool.poetry.scripts]
aipython = 'aipython.__main__:run'

[tool.poetry.dependencies]
python = "^3.8"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.isort]
profile = "black"
line_length = 121
atomic = true
combine_as_imports = true
lines_between_types = 1

[tool.black]
target-version = ['py310']
line-length = 121

[tool.mypy]
python_version = "3.10"

show_column_numbers = true
show_error_codes = true

# same as mypy --strict
disallow_subclassing_any = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true

[[tool.mypy.overrides]]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=42", "wheel"]
build-backend = "poetry.core.masonry.api"