site_name: Benjy
repo_url: https://github.com/grai-io/benjy
repo_name: grai-io/benjy
site_favicon: favicon.svg


nav:
    - Home: index.md
    - 'User Guide': 
        - Installation: user_guide/installation.md
        - "Getting Started": user_guide/getting_started.md
        - Components: user_guide/components.md
    - API: reference/
    - cli: cli.md


markdown_extensions:
    - mkdocs_click
    - smarty
    - wikilinks
    - toc
    - admonition
    - sane_lists
    - codehilite
    - meta
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
    - search
    - mermaid2
    - section-index
    - gen-files:
        scripts:
        - docs/gen_ref_pages.py
    - literate-nav:
        nav_file: SUMMARY.md
    - mkdocstrings:
        default_handler: python
        watch:
          - src/benjy
        handlers:
          python:
            rendering:
              show_submodules: no
              show_source: no

    - macros
    - mkdocs-jupyter


theme:
  name: material
  logo: assets/icon-logo-0.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - header.autohide
    - navigation.sections
    - navigation.top
    - toc.integrate
