[tool.poetry]
name = "ecsmgmt-cli"
version = "0.2.1"
description = "Small CLI tool for interacting with the ECS Management API"
authors = ["Dominik Rimpf <dominik.rimpf@kit.edu>"]
license = "MPL-2.0"

readme = "README.md"
repository = "https://gitlab.com/domrim/ecsmgmt-cli"
homepage = "https://gitlab.com/domrim/ecsmgmt-cli"
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Intended Audience :: System Administrators",
]
include = [
    "LICENSE",
]
packages = [
    { include = "ecsmgmt" }
]

[tool.poetry.dependencies]
python = "^3.7"
python-ecsclient = "^1.1.11"
click = "^8.0.1"
PyYAML = "^5.4.1"
tabulate = "^0.8.9"
inquirer = "^2.7.0"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"

[tool.poetry.scripts]
ecsmgmt = 'ecsmgmt:cli'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
