# coding: utf-8

"""
    BAPP API

    This is the primary API for BAPP platform development  # noqa: E501

    OpenAPI spec version: v1
    Contact: office@cbsoft.ro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bapp_api_client
from bapp_api_client.models.inline_response200163 import InlineResponse200163  # noqa: E501
from bapp_api_client.rest import ApiException


class TestInlineResponse200163(unittest.TestCase):
    """InlineResponse200163 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200163(self):
        """Test InlineResponse200163"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bapp_api_client.models.inline_response200163.InlineResponse200163()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
