[build-system]
requires = [
    "setuptools>=46.4.0",
    "wheel",
    "Cython>=0.29.21,<3.0",
    'numpy==1.19.5;python_version<"3.10"',
    'numpy==1.21.4;python_version>="3.10"',
]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
source = [
    "dimod/",
    ]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "RuntimeError",
    "pass",
]
