[tool.poetry]
name = "ehelply-updater"
version = "0.1.6"
description = ""
authors = ["Shawn Clake <shawn.clake@gmail.com>"]
readme = "readme.md"
homepage = "https://ehelply.com"


[tool.poetry.dependencies]
python = ">=3.8"
wheel = "^0.36.2"
requests = "^2.25.1"
python-slugify = "^5.0.2"
pydantic = "^1.8.2"
ehelply-logger = "^0.0.8"
click = "^7.1.1"


[tool.poetry.dev-dependencies]
pytest = "^5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
