[tool.poetry]
name = "gw_frequencies"
version = "0.1.0"
description = "A convenience package to make reduced frequency arrays for the representation of gravitational waveforms."
authors = ["jacopok <jacopok@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8, <3.11"
numpy = "^1.20"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
