# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-09 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_v2', '0006_auto_20170207_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
