# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 08:11
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_v2', '0011_organisation_to_aims'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisationprofile',
            options={'base_manager_name': '_plain_manager'},
        ),
        migrations.AlterModelManagers(
            name='organisationprofile',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
