# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-09 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_v2', '0012_auto_20180123_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationcontactinfo',
            name='fax',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
