# coding: utf-8

"""
    BAPP API

    This is the primary API for BAPP platform development  # noqa: E501

    OpenAPI spec version: v1
    Contact: office@cbsoft.ro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bapp_api_client
from bapp_api_client.api.announcement_api import AnnouncementApi  # noqa: E501
from bapp_api_client.rest import ApiException


class TestAnnouncementApi(unittest.TestCase):
    """AnnouncementApi unit test stubs"""

    def setUp(self):
        self.api = bapp_api_client.api.announcement_api.AnnouncementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_announcement_announcements_attachments_create(self):
        """Test case for announcement_announcements_attachments_create

        """
        pass

    def test_announcement_announcements_attachments_delete(self):
        """Test case for announcement_announcements_attachments_delete

        """
        pass

    def test_announcement_announcements_attachments_list(self):
        """Test case for announcement_announcements_attachments_list

        """
        pass

    def test_announcement_announcements_attachments_partial_update(self):
        """Test case for announcement_announcements_attachments_partial_update

        """
        pass

    def test_announcement_announcements_attachments_read(self):
        """Test case for announcement_announcements_attachments_read

        """
        pass

    def test_announcement_announcements_attachments_update(self):
        """Test case for announcement_announcements_attachments_update

        """
        pass

    def test_announcement_announcements_create(self):
        """Test case for announcement_announcements_create

        """
        pass

    def test_announcement_announcements_delete(self):
        """Test case for announcement_announcements_delete

        """
        pass

    def test_announcement_announcements_list(self):
        """Test case for announcement_announcements_list

        """
        pass

    def test_announcement_announcements_partial_update(self):
        """Test case for announcement_announcements_partial_update

        """
        pass

    def test_announcement_announcements_read(self):
        """Test case for announcement_announcements_read

        """
        pass

    def test_announcement_announcements_send_notifications(self):
        """Test case for announcement_announcements_send_notifications

        """
        pass

    def test_announcement_announcements_update(self):
        """Test case for announcement_announcements_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
