[tool.poetry]
name = "backend-utils"
version = "0.2.0"
description = "backend utils"
authors = ["Mark Antipin <antipinsuperstar@yandex.ru>"]
readme = "README.md"
homepage = "https://github.com/Sistemka/backend-utils"
repository = "https://github.com/Sistemka/backend-utils.git"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.75.0"
httpx = "^0.22.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
flake8-import-order = "^0.18.1"
flake8-bugbear = "^22.3.23"
flake8 = "^4.0.1"
flake8-eradicate = "^1.2.0"
flake8-builtins = "^1.5.3"
flake8-comprehensions = "^3.8.0"
flake8-broken-line = "^0.4.0"
flake8-print = "^4.0.0"
pep8-naming = "^0.12.1"
flake8-unused-arguments = "^0.0.9"
coverage = "^6.3.2"
respx = "^0.19.2"
pytest-asyncio = "^0.18.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
