[build-system]
requires = ["setuptools", "wheel", "versioneer-518"]  # PEP 508 specifications.

######
# MyPy
######
[tool.mypy]
show_error_codes = true
check_untyped_defs = true
disallow_any_explicit = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_reexport = false
pretty = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
files = "fidescls/"
exclude = "fidescls/_version.py"

#######
# Black
#######
[tool.black]
py39 = true
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist

    # The following are specific to Black, you probably don't want those.
    | blib2to3
    | tests/data
)/
'''

########
# Pylint
########
[tool.pylint.messages_control]
ignore="migrations"
disable=[
    "line-too-long",
    "too-few-public-methods",
    "duplicate-code",
    "import-error",
    "unused-argument",
    "no-self-use",
    "import-outside-toplevel",
    "unsubscriptable-object", # Otherwise throws errors on certain Type annotations
    "too-many-arguments",
    "missing-module-docstring",
    "raise-missing-from",
    "fixme",
    "logging-fstring-interpolation",
    "cell-var-from-loop",
    "dangerous-default-value",
    "c-extension-no-member"  # for spacy inports throwing errors
]
extension-pkg-whitelist = "pydantic"

[tool.pylint.reports]
reports="no"
output-format="colorized"

[tool.pylint.format]
max-line-length="88"

[tool.pylint.basic]
good-names="_,i,setUp,tearDown,maxDiff,default_app_config"

########
# Pytest
########
[tool.pytest.ini_options]
testpaths="tests"
log_level = "DEBUG"
addopts = ["--cov=fidescls.api",
            "--cov=fidescls.cls",
            "--cov-report=term-missing",
            "-vv",
            "--no-cov-on-fail",
            "--disable-pytest-warnings"]
