[tool.poetry]
name = "ceresdb-python"
version = "1.0.1"
description = ""
authors = ["John Carter <john.carter@leapyear.io>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
