
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-14T11:25:45+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "560e2208a8edbe6ad51aa91c33bef5ce4745dbcc",
 "version": "2022.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
