from .exceptions import LoginError as LoginError, NotLoggedIn as NotLoggedIn, TokenExpired as TokenExpired
from typing import Any

class ToyotaOneAuth:
    ACCESS_TOKEN_URL: str
    AUTHORIZE_URL: str
    AUTHENTICATE_URL: str
    def __init__(self, callback: Any | None = ..., initial_tokens: Any | None = ..., refresh_secs: int = ...) -> None: ...
    async def authorize(self, username, password): ...
    async def refresh_tokens(self) -> None: ...
    async def request_tokens(self, code) -> None: ...
    async def check_tokens(self) -> None: ...
    async def login(self, username, password) -> None: ...
    def logged_in(self): ...
    async def get_access_token(self): ...
    async def get_guid(self): ...
    async def get_id_info(self): ...
    def get_tokens(self): ...
    def set_tokens(self, tokens) -> None: ...
    def get_device_id(self): ...
    def set_device_id(self, device_id) -> None: ...
