[tool.poetry]
name = "eth-rec"
version = "0.1.2.4"
description = "Download ETH-Livestream"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
eth-rec = 'eth_rec.eth_rec:main'
