[tool.poetry]
name = "img-dice"
version = "0.3.0"
description = "Dice tif images into smaller sections using a shapefile of polygons"
authors = ["Taylor Denouden <taylor.denouden@hakai.org>"]
license = "MIT"
repository = "https://github.com/tayden/img-dice-py"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
fire = "^0.4.0"
pyshp = "^2.2.0"
PySide2 = "^5.15.2"
rasterio = "^1.2.10"

[tool.poetry.dev-dependencies]
pyinstaller = "^4.10"

[tool.poetry.scripts]
img-dice = 'img_dice.cli:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
