# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 09:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('oipa', '0001_initial'), ('oipa', '0002_auto_20180801_1811'), ('oipa', '0003_auto_20180801_1811'), ('oipa', '0004_oipabridgelink'), ('oipa', '0005_auto_20180829_1522'), ('oipa', '0006_oipasyncrecord_cg_added'), ('oipa', '0007_auto_20180905_1318'), ('oipa', '0008_auto_20180907_1712'), ('oipa', '0009_auto_20180913_1637'), ('oipa', '0010_auto_20180913_1741'), ('oipa', '0011_remove_oipaactivitylink_oipa_last_sync'), ('oipa', '0012_auto_20180920_1821')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OipaActivityLink',
            fields=[
                ('activity_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('oipa_linked', models.BooleanField(default=False)),
                ('oipa_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), choices=[('B', 'Budgets'), ('C', 'Commitments'), ('OF', 'Outgoing Funds'), ('IF', 'Incoming Funds')], default=list, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='OipaSyncRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_id', models.CharField(max_length=150)),
                ('c_added', models.IntegerField(default=0)),
                ('of_added', models.IntegerField(default=0)),
                ('b_added', models.IntegerField(default=0)),
                ('sync_datetime', models.DateTimeField(default=None, null=True)),
                ('if_added', models.IntegerField(default=0)),
            ],
        ),
    ]
