# coding: utf-8

"""
    BAPP API

    This is the primary API for BAPP platform development  # noqa: E501

    OpenAPI spec version: v1
    Contact: office@cbsoft.ro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bapp_api_client.configuration import Configuration


class TravelSheet(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'items': 'list[TravelSheetItem]',
        'created_at': 'datetime',
        'modified_at': 'datetime',
        'pdf_file': 'str',
        'start_fuel': 'str',
        '_date': 'date',
        'draft': 'bool',
        'number': 'str',
        'created_by': 'str',
        'modified_by': 'str',
        'car': 'int',
        'driver': 'int'
    }

    attribute_map = {
        'id': 'id',
        'items': 'items',
        'created_at': 'created_at',
        'modified_at': 'modified_at',
        'pdf_file': 'pdf_file',
        'start_fuel': 'start_fuel',
        '_date': 'date',
        'draft': 'draft',
        'number': 'number',
        'created_by': 'created_by',
        'modified_by': 'modified_by',
        'car': 'car',
        'driver': 'driver'
    }

    def __init__(self, id=None, items=None, created_at=None, modified_at=None, pdf_file=None, start_fuel=None, _date=None, draft=None, number=None, created_by=None, modified_by=None, car=None, driver=None, _configuration=None):  # noqa: E501
        """TravelSheet - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._items = None
        self._created_at = None
        self._modified_at = None
        self._pdf_file = None
        self._start_fuel = None
        self.__date = None
        self._draft = None
        self._number = None
        self._created_by = None
        self._modified_by = None
        self._car = None
        self._driver = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if items is not None:
            self.items = items
        if created_at is not None:
            self.created_at = created_at
        if modified_at is not None:
            self.modified_at = modified_at
        if pdf_file is not None:
            self.pdf_file = pdf_file
        self.start_fuel = start_fuel
        self._date = _date
        if draft is not None:
            self.draft = draft
        if number is not None:
            self.number = number
        if created_by is not None:
            self.created_by = created_by
        if modified_by is not None:
            self.modified_by = modified_by
        self.car = car
        if driver is not None:
            self.driver = driver

    @property
    def id(self):
        """Gets the id of this TravelSheet.  # noqa: E501


        :return: The id of this TravelSheet.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TravelSheet.


        :param id: The id of this TravelSheet.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def items(self):
        """Gets the items of this TravelSheet.  # noqa: E501


        :return: The items of this TravelSheet.  # noqa: E501
        :rtype: list[TravelSheetItem]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this TravelSheet.


        :param items: The items of this TravelSheet.  # noqa: E501
        :type: list[TravelSheetItem]
        """

        self._items = items

    @property
    def created_at(self):
        """Gets the created_at of this TravelSheet.  # noqa: E501

        Date and time at which this record was added  # noqa: E501

        :return: The created_at of this TravelSheet.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this TravelSheet.

        Date and time at which this record was added  # noqa: E501

        :param created_at: The created_at of this TravelSheet.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def modified_at(self):
        """Gets the modified_at of this TravelSheet.  # noqa: E501

        Date and time at which this record was modified  # noqa: E501

        :return: The modified_at of this TravelSheet.  # noqa: E501
        :rtype: datetime
        """
        return self._modified_at

    @modified_at.setter
    def modified_at(self, modified_at):
        """Sets the modified_at of this TravelSheet.

        Date and time at which this record was modified  # noqa: E501

        :param modified_at: The modified_at of this TravelSheet.  # noqa: E501
        :type: datetime
        """

        self._modified_at = modified_at

    @property
    def pdf_file(self):
        """Gets the pdf_file of this TravelSheet.  # noqa: E501


        :return: The pdf_file of this TravelSheet.  # noqa: E501
        :rtype: str
        """
        return self._pdf_file

    @pdf_file.setter
    def pdf_file(self, pdf_file):
        """Sets the pdf_file of this TravelSheet.


        :param pdf_file: The pdf_file of this TravelSheet.  # noqa: E501
        :type: str
        """

        self._pdf_file = pdf_file

    @property
    def start_fuel(self):
        """Gets the start_fuel of this TravelSheet.  # noqa: E501


        :return: The start_fuel of this TravelSheet.  # noqa: E501
        :rtype: str
        """
        return self._start_fuel

    @start_fuel.setter
    def start_fuel(self, start_fuel):
        """Sets the start_fuel of this TravelSheet.


        :param start_fuel: The start_fuel of this TravelSheet.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and start_fuel is None:
            raise ValueError("Invalid value for `start_fuel`, must not be `None`")  # noqa: E501

        self._start_fuel = start_fuel

    @property
    def _date(self):
        """Gets the _date of this TravelSheet.  # noqa: E501


        :return: The _date of this TravelSheet.  # noqa: E501
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this TravelSheet.


        :param _date: The _date of this TravelSheet.  # noqa: E501
        :type: date
        """
        if self._configuration.client_side_validation and _date is None:
            raise ValueError("Invalid value for `_date`, must not be `None`")  # noqa: E501

        self.__date = _date

    @property
    def draft(self):
        """Gets the draft of this TravelSheet.  # noqa: E501


        :return: The draft of this TravelSheet.  # noqa: E501
        :rtype: bool
        """
        return self._draft

    @draft.setter
    def draft(self, draft):
        """Sets the draft of this TravelSheet.


        :param draft: The draft of this TravelSheet.  # noqa: E501
        :type: bool
        """

        self._draft = draft

    @property
    def number(self):
        """Gets the number of this TravelSheet.  # noqa: E501


        :return: The number of this TravelSheet.  # noqa: E501
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this TravelSheet.


        :param number: The number of this TravelSheet.  # noqa: E501
        :type: str
        """
        if (self._configuration.client_side_validation and
                number is not None and len(number) > 30):
            raise ValueError("Invalid value for `number`, length must be less than or equal to `30`")  # noqa: E501

        self._number = number

    @property
    def created_by(self):
        """Gets the created_by of this TravelSheet.  # noqa: E501

        User id that created this record  # noqa: E501

        :return: The created_by of this TravelSheet.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this TravelSheet.

        User id that created this record  # noqa: E501

        :param created_by: The created_by of this TravelSheet.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def modified_by(self):
        """Gets the modified_by of this TravelSheet.  # noqa: E501

        Last user id that modified this record  # noqa: E501

        :return: The modified_by of this TravelSheet.  # noqa: E501
        :rtype: str
        """
        return self._modified_by

    @modified_by.setter
    def modified_by(self, modified_by):
        """Sets the modified_by of this TravelSheet.

        Last user id that modified this record  # noqa: E501

        :param modified_by: The modified_by of this TravelSheet.  # noqa: E501
        :type: str
        """

        self._modified_by = modified_by

    @property
    def car(self):
        """Gets the car of this TravelSheet.  # noqa: E501


        :return: The car of this TravelSheet.  # noqa: E501
        :rtype: int
        """
        return self._car

    @car.setter
    def car(self, car):
        """Sets the car of this TravelSheet.


        :param car: The car of this TravelSheet.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and car is None:
            raise ValueError("Invalid value for `car`, must not be `None`")  # noqa: E501

        self._car = car

    @property
    def driver(self):
        """Gets the driver of this TravelSheet.  # noqa: E501


        :return: The driver of this TravelSheet.  # noqa: E501
        :rtype: int
        """
        return self._driver

    @driver.setter
    def driver(self, driver):
        """Sets the driver of this TravelSheet.


        :param driver: The driver of this TravelSheet.  # noqa: E501
        :type: int
        """

        self._driver = driver

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TravelSheet, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TravelSheet):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TravelSheet):
            return True

        return self.to_dict() != other.to_dict()
