[tool.poetry]
name = "mlfoundry-ui"
version = "0.1.5"
description = "Dashboard code for mlfoundry"
authors = ["Abhishek Choudhary <abhichoudhary06@gmail.com>"]
homepage = "https://github.com/truefoundry/mlfoundry-ui"
repository = "https://github.com/truefoundry/mlfoundry-ui"
readme = "README.md"
packages = [
    { include = "mlfoundry_ui" },
]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
whylogs = ">=0.6.15"
numpy = ">=1.17.0"
pandas = ">=1.0.0"
streamlit = "^1.3.0"
hydralit = "^1.0.10"
plotly = "^5.5.0"
matplotlib = ">=3.0.3"
mlfoundry = ">=0.1.9"

[[tool.poetry.source]]
name = "packagr"
url = "https://api.packagr.app/GRf2Xs5a"
secondary = true

[tool.poetry-dynamic-versioning]
enable = true

[tool.poetry.dev-dependencies]
pre-commit = "^2.16.0"
pytest = "^6.2"

[tool.poetry.plugins."console_scripts"]
mlfoundry_ui = "mlfoundry_ui.cli.cli_interface:create_mlfoundry_ui_cli"

[tool.black]
line-length = 88
safe = true
target_version = ["py36", "py37", "py38", "py39"]

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"
