[tool.poetry]
name = "gsp"
version = "0.4.0"
description = "Google Sheet Poster"
authors = ["juke <juke@free.fr>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.4.0"
gspread = "^5.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
