[tool.poetry]
name = "nornir_routeros"
version = "0.4.0"
description = "RouterOS API plugins for nornir"
authors = ["Devon Mar <devonm@mdmm.ca>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.6"
RouterOS-api = "^0.17.0"
Jinja2 = "^2.11.2|^3.0"
pytest-cov = "^3.0.0"

[tool.poetry.dev-dependencies]
Sphinx = "^4.2"
sphinx-rtd-theme = "^0.5.0"
sphinx-autodoc-typehints = "^1.11.1"
nornir = "^3.0.0"
pytest = "^6.2.5"
flake8 = "^4.0.1"

[tool.poetry.plugins."nornir.plugins.connections"]
"routerosapi" = "nornir_routeros.plugins.connections:RouterOsApi"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
