# coding: utf-8

"""
    [OpenBoxes](https://openboxes.org) is an open-source LMIS application that increases stock visibility, reduces the risk of stock-outs and stock wastage, and offers tools to improve forecasting and traceability.

    OpenAPI spec version: 0.8.17

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "openboxes-client"
VERSION = "0.1a2"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="OpenBoxes REST API client",
    author_email="",
    url="https://openboxes.org",
    keywords=["Swagger", "OpenBoxes", "REST", "API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    [OpenBoxes](https://openboxes.org) is an open-source LMIS application that increases stock visibility, reduces the risk of stock-outs and stock wastage, and offers tools to improve forecasting and traceability.
    """,
    long_description_content_type='text/markdown',
    python_requires=">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*",
    classifiers=[
    	"Development Status :: 1 - Planning",
    	"Intended Audience :: Developers",
    	"Intended Audience :: Healthcare Industry",
    	"Intended Audience :: Information Technology",
    	"License :: OSI Approved :: Eclipse Public License 1.0 (EPL-1.0)",
    	"Natural Language :: English",
    	"Operating System :: OS Independent",
    	"Programming Language :: Python :: 2.7",
    	"Programming Language :: Python :: 3.4",
    	"Programming Language :: Python :: 3.5",
    	"Programming Language :: Python :: 3.6",
    	"Programming Language :: Python :: 3.7",
    	"Programming Language :: Python :: 3.8",
		"Programming Language :: Python :: 3.9",
    	"Topic :: Software Development :: Libraries",
    ]
)
