from .auth import ToyotaOneAuth as ToyotaOneAuth
from typing import Any

class ToyotaOneClient:
    API_GATEWAY: str
    API_KEY: str
    auth: Any
    def __init__(self, auth: Any | None = ...) -> None: ...
    async def api_request(self, method, endpoint, header_params: Any | None = ..., **kwargs): ...
    async def api_get(self, endpoint, header_params: Any | None = ...): ...
    async def api_post(self, endpoint, json, header_params: Any | None = ...): ...
    async def get_user_vehicle_list(self): ...
    async def get_vehicle_detail(self, vin): ...
    async def get_vehicle_health_report(self, vin): ...
    async def get_vehicle_health_status(self, vin): ...
    async def get_telemetry(self, vin, generation: str = ...): ...
    async def get_vehicle_status(self, vin, generation: str = ...): ...
    async def get_vehicle_status_17cy(self, vin): ...
    async def get_vehicle_status_17cyplus(self, vin): ...
    async def get_engine_status(self, vin, generation: str = ...): ...
    async def get_engine_status_17cy(self, vin): ...
    async def get_engine_status_17cyplus(self, vin): ...
    async def send_refresh_status(self, vin, generation: str = ...): ...
    async def send_refresh_request_17cy(self, vin): ...
    async def send_refresh_request_17cyplus(self, vin): ...
    async def remote_request(self, vin, command, value: Any | None = ..., generation: str = ...): ...
    async def remote_request_17cy(self, vin, command, value): ...
    async def remote_request_17cyplus(self, vin, command): ...
