
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-14T08:57:26+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9248f13aab26b23996cdc2ba71361b8f6ec0b4aa",
 "version": "2647"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
