[tool.poetry]
name = "mini_scripts"
version = "0.1.0"
description = ""
authors = ["lordralinc"]

[tool.poetry.dependencies]
python = ">=3.8"
pytz = {version = ">=2022.1", optional = true}
pymorphy2 = {version = ">=0.9.1", optional = true}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

