[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.mypy]
check_untyped_defs = true
no_implicit_optional = true
warn_unused_configs = true
#plugins = "sqlmypy"
exclude = [
  "phidata/asset/dev", # exclude dev assets from mypy
  "phidata/workflow/dev", # exclude dev workflows from mypy
  "phidata/product/dev", # exclude dev products from mypy
]

[[tool.mypy.overrides]]
module = [
  "git",
  "setuptools",
  "boto3",
  "boto3.*",
  "botocore",
  "botocore.*",
  "typer",
  "tiingo",
  "docker.*",
  "airflow.*",
  "pandas.*",
  "kubernetes.*",
]
ignore_missing_imports = true
