[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
default_section = "THIRDPARTY"
known_first_party = ["lifter-api-wrapper"]
known_third_party = ["pytest", "requests", "setuptools"]

[tool.black]
line-length = 88
include = '\.pyi?%'

[tool.pydocstyle]
match = ".*/.py"
