player_cmd = "mpv {url} --chapters-file=/tmp/lyberry_chapters --force-media-title={title}"
viewer_cmd = "xdg-open {file}"
lbrynet_api = "http://localhost:5279"
comment_api = "https://comments.odysee.com/api/v2"
lighthouse_api = "https://lighthouse.odysee.tv"
default_wallet = "default_wallet"

