
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-08T16:14:04-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "95d62c9bab55acb753f3c7ec3daed3f86339cf3e",
 "version": "1.4.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
