
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-13T14:31:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cfee10a16bfdaf9e894317b04efd5563933b0ce4",
 "version": "v2.9.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
