[tool.poetry]
name = "todo-cli-typer"
version = "0.3.3"
description = "CLI Todo app with typer and sqlite"
authors = ["Xinyuan Chen <45612704+tddschn@users.noreply.github.com>"]

[tool.poetry.scripts]
todo = "todo_cli_typer.__main__:main"

[tool.poetry.dependencies]
python = "^3.10"
typer = "0.3.2"
colorama = "0.4.4"
shellingham = "1.4.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
bump2version = "^1.0.1"
yapf = "^0.32.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
