[tool.poetry]
name = "polarbears"
version = "0.0.0"
description = ""
authors = ["Chris Pryer"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
polars = "^0.13.16"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
pytest = "^7.1.1"
mypy = "^0.942"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
