apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-artifacts
  namespace: spell-run
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "128Gi"
  storageClassName: gp2
  volumeMode: Filesystem
