[tool.poetry]
name = "taospy"
version = "2.2.5"
description = "TDengine connector for python"
authors = ["Taosdata Inc. <support@taosdata.com>"]
license = "AGPL-3.0"
readme = "README.md"
packages = [
  {include = "taos"}
]

[tool.poetry.plugins] # Optional super table

[tool.poetry.plugins."sqlalchemy.dialects"]
"taos" = "taos.sqlalchemy:TaosDialect"

[tool.poetry.dependencies]
python = "^2.7 || >=3.6"
pytz = "*"

[tool.poetry.dev-dependencies]
typing = "*"
pytest = [
  { version = "^4.6", python = ">=2.7,<3.0" },
  { version = "^6.2", python = ">=3.7,<4.0" }
]
pdoc = { version = "^7.1.1", python = "^3.7" }
mypy = { version = "^0.910", python = "^3.6" }
black = [{ version = "^21.*", python = ">=3.6.2,<4.0" }]
SQLAlchemy = { version = "^1.4", python=">=2.7 || >=3.6,<4.0", optional = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119
