# coding: utf-8

"""
    BAPP API

    This is the primary API for BAPP platform development  # noqa: E501

    OpenAPI spec version: v1
    Contact: office@cbsoft.ro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bapp_api_client.configuration import Configuration


class FiscalReceiptItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'quantity': 'str',
        'price': 'str',
        'parent': 'int',
        'product': 'int'
    }

    attribute_map = {
        'id': 'id',
        'quantity': 'quantity',
        'price': 'price',
        'parent': 'parent',
        'product': 'product'
    }

    def __init__(self, id=None, quantity=None, price=None, parent=None, product=None, _configuration=None):  # noqa: E501
        """FiscalReceiptItem - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._quantity = None
        self._price = None
        self._parent = None
        self._product = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if quantity is not None:
            self.quantity = quantity
        if price is not None:
            self.price = price
        self.parent = parent
        self.product = product

    @property
    def id(self):
        """Gets the id of this FiscalReceiptItem.  # noqa: E501


        :return: The id of this FiscalReceiptItem.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FiscalReceiptItem.


        :param id: The id of this FiscalReceiptItem.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def quantity(self):
        """Gets the quantity of this FiscalReceiptItem.  # noqa: E501


        :return: The quantity of this FiscalReceiptItem.  # noqa: E501
        :rtype: str
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this FiscalReceiptItem.


        :param quantity: The quantity of this FiscalReceiptItem.  # noqa: E501
        :type: str
        """

        self._quantity = quantity

    @property
    def price(self):
        """Gets the price of this FiscalReceiptItem.  # noqa: E501


        :return: The price of this FiscalReceiptItem.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this FiscalReceiptItem.


        :param price: The price of this FiscalReceiptItem.  # noqa: E501
        :type: str
        """

        self._price = price

    @property
    def parent(self):
        """Gets the parent of this FiscalReceiptItem.  # noqa: E501


        :return: The parent of this FiscalReceiptItem.  # noqa: E501
        :rtype: int
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this FiscalReceiptItem.


        :param parent: The parent of this FiscalReceiptItem.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and parent is None:
            raise ValueError("Invalid value for `parent`, must not be `None`")  # noqa: E501

        self._parent = parent

    @property
    def product(self):
        """Gets the product of this FiscalReceiptItem.  # noqa: E501


        :return: The product of this FiscalReceiptItem.  # noqa: E501
        :rtype: int
        """
        return self._product

    @product.setter
    def product(self, product):
        """Sets the product of this FiscalReceiptItem.


        :param product: The product of this FiscalReceiptItem.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and product is None:
            raise ValueError("Invalid value for `product`, must not be `None`")  # noqa: E501

        self._product = product

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FiscalReceiptItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FiscalReceiptItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FiscalReceiptItem):
            return True

        return self.to_dict() != other.to_dict()
