# coding: utf-8

"""
    BAPP API

    This is the primary API for BAPP platform development  # noqa: E501

    OpenAPI spec version: v1
    Contact: office@cbsoft.ro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bapp_api_client
from bapp_api_client.models.inline_response200166 import InlineResponse200166  # noqa: E501
from bapp_api_client.rest import ApiException


class TestInlineResponse200166(unittest.TestCase):
    """InlineResponse200166 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200166(self):
        """Test InlineResponse200166"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bapp_api_client.models.inline_response200166.InlineResponse200166()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
