from .core import Storage as Storage
from pathlib import Path
from typing import Union

class LocalStorage(Storage):
    def __init__(self, root: Union[Path, str], create: bool = ..., **kwargs) -> None: ...
    def exists(self, key: str) -> bool: ...
    def save(self, key: str, data: bytes) -> None: ...
    def load(self, key: str) -> bytes: ...
    def delete(self, key: str): ...
