from .core import Storage as Storage

class MemoryStorage(Storage):
    def __init__(self, **kwargs) -> None: ...
    def exists(self, key: str) -> bool: ...
    def load(self, key: str) -> bytes: ...
    def save(self, key: str, data: bytes): ...
    def delete(self, key: str): ...
