# coding: utf-8

"""
    BAPP API

    This is the primary API for BAPP platform development  # noqa: E501

    OpenAPI spec version: v1
    Contact: office@cbsoft.ro
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bapp_api_client
from bapp_api_client.api.receipt_api import ReceiptApi  # noqa: E501
from bapp_api_client.rest import ApiException


class TestReceiptApi(unittest.TestCase):
    """ReceiptApi unit test stubs"""

    def setUp(self):
        self.api = bapp_api_client.api.receipt_api.ReceiptApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_receipt_cash_register_create(self):
        """Test case for receipt_cash_register_create

        """
        pass

    def test_receipt_cash_register_delete(self):
        """Test case for receipt_cash_register_delete

        """
        pass

    def test_receipt_cash_register_list(self):
        """Test case for receipt_cash_register_list

        """
        pass

    def test_receipt_cash_register_partial_update(self):
        """Test case for receipt_cash_register_partial_update

        """
        pass

    def test_receipt_cash_register_read(self):
        """Test case for receipt_cash_register_read

        """
        pass

    def test_receipt_cash_register_update(self):
        """Test case for receipt_cash_register_update

        """
        pass

    def test_receipt_fiscal_receipt_create(self):
        """Test case for receipt_fiscal_receipt_create

        """
        pass

    def test_receipt_fiscal_receipt_delete(self):
        """Test case for receipt_fiscal_receipt_delete

        """
        pass

    def test_receipt_fiscal_receipt_item_create(self):
        """Test case for receipt_fiscal_receipt_item_create

        """
        pass

    def test_receipt_fiscal_receipt_item_delete(self):
        """Test case for receipt_fiscal_receipt_item_delete

        """
        pass

    def test_receipt_fiscal_receipt_item_list(self):
        """Test case for receipt_fiscal_receipt_item_list

        """
        pass

    def test_receipt_fiscal_receipt_item_partial_update(self):
        """Test case for receipt_fiscal_receipt_item_partial_update

        """
        pass

    def test_receipt_fiscal_receipt_item_read(self):
        """Test case for receipt_fiscal_receipt_item_read

        """
        pass

    def test_receipt_fiscal_receipt_item_update(self):
        """Test case for receipt_fiscal_receipt_item_update

        """
        pass

    def test_receipt_fiscal_receipt_list(self):
        """Test case for receipt_fiscal_receipt_list

        """
        pass

    def test_receipt_fiscal_receipt_partial_update(self):
        """Test case for receipt_fiscal_receipt_partial_update

        """
        pass

    def test_receipt_fiscal_receipt_read(self):
        """Test case for receipt_fiscal_receipt_read

        """
        pass

    def test_receipt_fiscal_receipt_update(self):
        """Test case for receipt_fiscal_receipt_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
