# Generated by Django 3.2.13 on 2022-04-13 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simpel_pages', '0006_auto_20220413_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='First published at'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_menu',
            field=models.BooleanField(default=False, verbose_name='show in menu'),
        ),
    ]
