
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-14T03:09:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6784ae5b8551e41c1c1fb710729edc01ed5a4ec6",
 "version": "0.0.73.post0.dev130"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
