
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-08T14:01:08-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e71239e177d76a9b8bdca64c6995b7727afc5a5",
 "version": "0.23.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
