# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-05 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0007_auto_20161007_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='openly_status',
            field=models.CharField(choices=[('iatixml', 'IATI XML'), ('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='iatixml', max_length=12),
        ),
        migrations.AlterField(
            model_name='activitytotalbudgetusd',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_budget_in', to='iati.Activity', verbose_name='Activity Budget in USD'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='openly_status',
            field=models.CharField(choices=[('iatixml', 'IATI XML'), ('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='iatixml', max_length=12),
        ),
        migrations.AlterField(
            model_name='transactionvalueusd',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='value_in', to='iati.Transaction', verbose_name='Transaction Value in USD'),
        ),
    ]
