# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-24 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0014_merge'),
        ('aims', '0012_auto_20170320_1348'),
    ]

    operations = [
    ]
