# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-03 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0009_categories_and_date_20170404_1556'),
        ('aims', '0020_activitylogmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEndorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aims.Activity')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iati.Organisation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='activityendorsement',
            unique_together=set([('activity', 'organisation')]),
        ),
    ]
