# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-01 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0020_activitylogmessage'),
        ('aims', '0020_auto_20170418_2059'),
    ]

    operations = [
    ]
