# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-17 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0026_governmentorganisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityendorsement',
            options={'permissions': (('can_edit_endorsements_and_status', 'Can do anything involving endorsements and publication status'),)},
        ),
    ]
