# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0055_merge_20180305_1415'),
        ('aims', '0058_organisationactivitybudgetsusd'),
    ]

    operations = [
    ]
