# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0062_drop_views'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='title',
            unique_together=set([('activity', 'language')]),
        ),
    ]
