# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-03-28 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0067_iati_id_not_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='internal_identifier',
            field=models.CharField(blank=True, max_length=150, null=True),
        )
    ]
