# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-11 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0068_activity_internal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlink',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aims.Organisation'),
        ),
        migrations.AlterField(
            model_name='documentlink',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aims.Activity'),
        ),
    ]
