# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0074_doc_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(db_index=True, max_length=2000),
        ),
    ]
