# Generated by Django 3.0.8 on 2020-07-10 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0085_auto_20200417_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionfinancials',
            name='exchangerate',
        ),
        migrations.RemoveField(
            model_name='transactionfinancials',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='activitycurrency',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activitycurrency',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='locationgeodata',
            name='location',
        ),
        migrations.DeleteModel(
            name='OrganisationBudgetsUsd',
        ),
        migrations.RemoveField(
            model_name='transactionvaluelocationsector',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='transactionvaluelocationsector',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transactionvaluelocationsector',
            name='location',
        ),
        migrations.RemoveField(
            model_name='transactionvaluelocationsector',
            name='region',
        ),
        migrations.RemoveField(
            model_name='transactionvaluelocationsector',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='transactionvaluelocationsector',
            name='township',
        ),
        migrations.RemoveField(
            model_name='transactionvaluelocationsector',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transactionvaluelocationview',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='transactionvaluelocationview',
            name='location',
        ),
        migrations.RemoveField(
            model_name='transactionvaluelocationview',
            name='region',
        ),
        migrations.RemoveField(
            model_name='transactionvaluelocationview',
            name='township',
        ),
        migrations.RemoveField(
            model_name='transactionvaluelocationview',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transactionvalueusd',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='TransactionFinancials',
        ),
        migrations.DeleteModel(
            name='ActivityCurrency',
        ),
        migrations.DeleteModel(
            name='LocationGeodata',
        ),
        migrations.DeleteModel(
            name='TransactionValueLocationSector',
        ),
        migrations.DeleteModel(
            name='TransactionValueLocationView',
        ),
        migrations.DeleteModel(
            name='transactionvalueusd',
        ),
    ]
