# Generated by Django 3.1 on 2020-10-02 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0086_sync_finance_views_20200710_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aims.activity'),
        ),
    ]
