# Generated by Django 3.1.13 on 2021-10-01 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import aims.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aims', '0093_transaction_auto_timestamps'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activitylogmessage',
            managers=[
                ('objects', aims.models.ActivityLogmessageManager()),
            ],
        ),
        migrations.AddField(
            model_name='activitylogmessage',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='aims.organisation'),
        ),
        migrations.AddField(
            model_name='activitylogmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
