[tool.poetry]
name = "camel-model"
version = "0.1.2"
description = ""
authors = ["todotom <tomasdarioam@protonmail.com>"]
packages = [
    { include = "./camel_model/**/*.py" },
]

[tool.poetry.dependencies]
python = "3.10.4"
pydantic = "1.9.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
