# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-15 22:36
from __future__ import unicode_literals

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0005_auto_20160812_0427'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activity',
            managers=[
                ('cleaner', django.db.models.manager.Manager()),
            ],
        ),
    ]
