# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-03 07:28
from __future__ import unicode_literals

from django.db import migrations


def migrate_bad_locations(apps, schema_editor):
    Location = apps.get_model('aims', 'Location')
    Location.objects.filter(type=None).update(
        ref='MM',
        adm_code='MM',
        type_id='ADMD',
        adm_country_adm1='Nation-wide'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0007_auto_20161007_1054'),
    ]

    operations = [
        migrations.RunPython(migrate_bad_locations)
    ]
