# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-03 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0008_auto_20170127_1518'),
        ('aims', '0008_auto_20170203_1628'),
    ]

    operations = [
    ]
