# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-05 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0014_documentupload_user'),
        ('aims', '0015_merge'),
    ]

    operations = [
    ]
