# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-17 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0017_auto_20170330_0920'),
    ]

    operations = [
    ]
