# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-24 07:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0019_auto_20170421_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tstamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aims.Activity')),
            ],
        ),
    ]
