# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-18 11:59
from __future__ import unicode_literals

# from django.core.management import call_command
from django.db import migrations


# this disabled due to adding a update_translation_fields call later in the migration list
# def update_translations(apps, schema_editor):
#    call_command('update_translation_fields', stdout=StringIO())


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0019_merge'),
    ]

    operations = [
        # this disabled due to adding a update_translation_fields call later in the migration list
        # migrations.RunPython(update_translations),
    ]
