# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-10 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0024_auto_20170508_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='openly_status',
            field=models.CharField(choices=[('iatixml', 'IATI XML'), ('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('blank', 'Blank'), ('review', 'Under review')], default='iatixml', max_length=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='openly_status',
            field=models.CharField(choices=[('iatixml', 'IATI XML'), ('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('blank', 'Blank'), ('review', 'Under review')], default='iatixml', max_length=12),
        ),
    ]
