# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-03 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0036_organisation_to_aims'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNarrative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', max_length=40000)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative', to='iati.DocumentLink')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iati.Language')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='documentnarrative',
            unique_together=set([('document', 'language')]),
        ),
    ]
