# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-29 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0039_iati_to_aims'),
        ('aims', '0039_activityaidtypebreakdown_activitycommitment'),
    ]

    operations = [
    ]
