# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0061_commitmenttotal'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            DROP VIEW IF EXISTS aims_activityaidtypebreakdown CASCADE;
            DROP VIEW IF EXISTS aims_activitycommitment CASCADE;
            DROP VIEW IF EXISTS aims_activitycurrency CASCADE;
            DROP VIEW IF EXISTS aims_aidtypeaggregate CASCADE;
            DROP VIEW IF EXISTS aims_transactionfinancials CASCADE;
            '''
        )
    ]
