# Generated by Django 2.2.12 on 2020-04-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0084_auto_20200228_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitystatus',
            options={'verbose_name_plural': 'Activity Statuses'},
        ),
        migrations.AddField(
            model_name='activitystatus',
            name='order',
            field=models.SmallIntegerField(help_text='Used to order the status options in dropdowns and filters.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activitystatus',
            name='language',
            field=models.CharField(default='en', help_text='Legacy field', max_length=2),
        ),
    ]
