[tool.poetry]
name = "ehelply-batcher"
version = "1.5.0"
description = ""
authors = ["Shawn Clake <shawn.clake@gmail.com>"]
readme = "readme.md"
homepage = "https://ehelply.com"


[tool.poetry.dependencies]
python = ">=3.10"
typer = "^0.4.1"
pytest-cov = "^3.0.0"
pytest-asyncio = "^0.18.3"
ehelply-logger = "^0.0.8"

[tool.poetry.dev-dependencies]
pytest = "^6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
