[tool.poetry]
name = "slai_cli"
version = "0.7.7"
description = ""
authors = ["slai <luke@slai.io>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0.0"
celery = "5.0.2"
redis = "^3.5.3"
boto3 = "^1.16.44"
shtab = "^1.3.4"
click = "^7.1.2"
python-dotenv = "^0.15.0"
Jinja2 = "^2.11.2"
GitPython = "^3.1.11"
Columnar = "^1.3.1"
PyDrive = "^1.3.1"
Flask = "^1.1.2"
Flask-Cors = "^3.0.9"
dill = "^0.3.3"
docker = "^5.0.0"
slai = "0.1.76"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
flake8-black = "^0.2.1"
flake8 = "^3.8.4"
black = {version = "^20.8b1", allow-prereleases = true}
typed-ast = "^1.4.2"
pip = "^21.1.2"
pytest = "^7.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
slai = 'slai_cli:main.main'

[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
