# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-23 02:03
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


def load_fixtures(apps, schema_editor):
    call_command('loaddata', 'indicatorvocabulary', app_label='iati_vocabulary')


class Migration(migrations.Migration):

    dependencies = [
        ('iati_vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures)
    ]
