"""
    Keycloak Admin REST API

    This is a REST API reference for the Keycloak Admin  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import keycloak_api
from keycloak_api.model.protocol_mapper_representation import ProtocolMapperRepresentation


class TestProtocolMapperRepresentation(unittest.TestCase):
    """ProtocolMapperRepresentation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProtocolMapperRepresentation(self):
        """Test ProtocolMapperRepresentation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProtocolMapperRepresentation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
