"""
    Keycloak Admin REST API

    This is a REST API reference for the Keycloak Admin  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import keycloak_api
from keycloak_api.model.access_token_cert_conf import AccessTokenCertConf


class TestAccessTokenCertConf(unittest.TestCase):
    """AccessTokenCertConf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessTokenCertConf(self):
        """Test AccessTokenCertConf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccessTokenCertConf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
