"""
    Keycloak Admin REST API

    This is a REST API reference for the Keycloak Admin  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import keycloak_api
from keycloak_api.model.authentication_execution_export_representation import AuthenticationExecutionExportRepresentation
globals()['AuthenticationExecutionExportRepresentation'] = AuthenticationExecutionExportRepresentation
from keycloak_api.model.authentication_flow_representation import AuthenticationFlowRepresentation


class TestAuthenticationFlowRepresentation(unittest.TestCase):
    """AuthenticationFlowRepresentation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthenticationFlowRepresentation(self):
        """Test AuthenticationFlowRepresentation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthenticationFlowRepresentation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
