"""
    Alvin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import alvin_api_client
from alvin_api_client.model.snowflake_account_details import SnowflakeAccountDetails
from alvin_api_client.model.snowflake_additional_config import SnowflakeAdditionalConfig
globals()['SnowflakeAccountDetails'] = SnowflakeAccountDetails
globals()['SnowflakeAdditionalConfig'] = SnowflakeAdditionalConfig
from alvin_api_client.model.data_platform_snowflake_create import DataPlatformSnowflakeCreate


class TestDataPlatformSnowflakeCreate(unittest.TestCase):
    """DataPlatformSnowflakeCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataPlatformSnowflakeCreate(self):
        """Test DataPlatformSnowflakeCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DataPlatformSnowflakeCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
