"""
    Alvin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import alvin_api_client
from alvin_api_client.model.data_entity_connection_type import DataEntityConnectionType


class TestDataEntityConnectionType(unittest.TestCase):
    """DataEntityConnectionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataEntityConnectionType(self):
        """Test DataEntityConnectionType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DataEntityConnectionType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
