"""
    Alvin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import alvin_api_client
from alvin_api_client.model.data_platform_job import DataPlatformJob
globals()['DataPlatformJob'] = DataPlatformJob
from alvin_api_client.model.limit_offset_page_data_platform_job import LimitOffsetPageDataPlatformJob


class TestLimitOffsetPageDataPlatformJob(unittest.TestCase):
    """LimitOffsetPageDataPlatformJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLimitOffsetPageDataPlatformJob(self):
        """Test LimitOffsetPageDataPlatformJob"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LimitOffsetPageDataPlatformJob()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
