"""
    Alvin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import alvin_api_client
from alvin_api_client.model.tableau_additional_config import TableauAdditionalConfig
from alvin_api_client.model.tableau_credentials import TableauCredentials
globals()['TableauAdditionalConfig'] = TableauAdditionalConfig
globals()['TableauCredentials'] = TableauCredentials
from alvin_api_client.model.data_platform_tableau_create import DataPlatformTableauCreate


class TestDataPlatformTableauCreate(unittest.TestCase):
    """DataPlatformTableauCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataPlatformTableauCreate(self):
        """Test DataPlatformTableauCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DataPlatformTableauCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
