"""
    Alvin

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import alvin_api_client
from alvin_api_client.model.user_role import UserRole
globals()['UserRole'] = UserRole
from alvin_api_client.model.user_get import UserGet


class TestUserGet(unittest.TestCase):
    """UserGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserGet(self):
        """Test UserGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
