[tool.poetry]
name = "hoodat-utils"
version = "0.0.4"
description = ""
authors = ["Eugene Brown <efbbrown@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
SQLAlchemy = "^1.4.35"
google-cloud-storage = "^2.2.1"
pytest = "^7.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
