[tool.poetry]
name = "captif-cpx"
version = "0.1"
description = ""
authors = ["John Bull <john.bull@nzta.govt.nz>"]
homepage = "https://github.com/johnbullnz/pyrsona"
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.4.2"
SoundFile = "^0.10.3"
pyramm = "^1.13"
pyrsona = "^0.4"
black = "^22.3.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pytest-randomly = "^3.11.0"
pytest-cov = "^2.12.1"
pre-commit = "^2.18.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
