[tool.poetry]
name = "contourheightmap"
version = "1.1.1"
description = "A fast python library and command line tool for generating topographic contour maps from heightmaps and images."
authors = ["Luke Miller <dodgyville@gmail.com>"]
license = "LGPLv3"
homepage = "https://gitlab.com/dodgyville/contourheightmap"
repository = "https://gitlab.com/dodgyville/contourheightmap"
readme = "README.md"
include = [
    "LICENSE",
]


[tool.poetry.dependencies]
python = "^3.8"
matplotlib = "^3.5.1"
Pillow = "^9.1.0"
numpy = "^1.22.3"
importlib = "^1.0.4"
typer = "^0.4.1"


[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pytest-cov = "^3.0.0"

[tool.poetry.scripts]
contourheightmap = "contourheightmap.cli:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
