[tool.poetry]
name = "harpar"
version = "0.0.2"
description = "A Pythonic Har File Parser written Python3"
authors = ["Dan Sikes <dansikes7@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
dacite = "^1.6.0"
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
