[tool.poetry]
name = "twita"
version = "0.0.2"
description = "Twitter Hidden API Library"
authors = ["DaRekaze <darekaze@gmail.com>"]
license = "LGPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/CounterTek/twita"
# documentation = "https://countertek.github.io/twita"
keywords = ["twitter", "twitter api"]
classifiers = [
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Developers",
]
packages = [
    { include = "twita"},
]

[tool.poetry.urls]
"Change Log" = "https://github.com/countertek/twita/blob/main/CHANGELOG.md"

[tool.poetry.dependencies]
python = "^3.8"
httpx = {extras = ["http2", "socks"], version = ">=0.21.0"}
aiometer = ">=0.3.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
black = {version = "^21.12b0", allow-prereleases = true}
pdoc = "^10.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
