[tool.poetry]
name = "optibioseq"
version = "0.1.3"
description = ""
authors = ["Iván Corona Guerrero <ivan.corona@uaq.mx> y Dr. Francisco Solis Munoz <siscomagma@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
openpyxl = "^3.0.9"
pandas = "^1.4.0"
numpy = "^1.22.2"
bs4 = "^0.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
