[build-system]
requires = ["mesonpep517", "meson==0.61.2", "ninja"] # PEP 508 specifications.
build-backend = "mesonpep517.buildapi"

[tool.mesonpep517.metadata]
author="Daniel Wagner"
author-email="dwagner@suse.de"
classifiers = [
    "Intended Audience :: Developers",
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
description-file="README.md"
home-page = "https://github.com/igaw/libimpel"
license="GPL-2.0-only"
requires-python=">=3.7"
summary="Python bindings for libimpel"

