
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-11T20:57:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "025e65c70f04ca0de8cc5255418aff82a4e982ac",
 "version": "0.0.73.post0.dev81"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
