
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-14T09:15:34-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0e04c00a4ff4746e21f5d8cb0a0f092434b00521",
 "version": "0.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
