fenics-compdata:
    stage: build
    image: "docker-registry.csc.mpi-magdeburg.mpg.de:5000/ci-images/fenics-images/2019-2:focal"
    before_script:
        # - pip3 install -r requirements.txt  # scipy numpy dolfin_navier_scipy
    script:
        - pip3 install .
        - cd simulations-training-data
        - mkdir train-data
        - mkdir simu-data
        - mkdir cached-data
        - source single-cylinder-tdp-sim.sh
        - source double-cylinder-tdp-sim.sh
    artifacts:
        paths:
            # - simulations-training-data/train-data/*.json
            - simulations-training-data/plots/*.png
            - simulations-training-data/plots/showthedata.md
    only:
        changes:
            - simulations-training-data/single-cylinder-tdp-sim.sh
            - simulations-training-data/double-cylinder-tdp-sim.sh
            - simulations-training-data/time_dep_nse_generic.py
            - .gitlab-ci.yml
            - requirements.txt

pytorch-unittest:
    stage: test
    image: "docker-registry.csc.mpi-magdeburg.mpg.de:5000/ci-images/fenics-images/2019-2:focal"
    before_script:
        - pip3 install .
        - pip3 install torch
    script:
        - cd tests
        - python3 test_units_cnnnse.py
