[project]
name = "cocolight"
readme = "README.rst"
requires-python = ">=3.8"
license = {file = "LICENSE.txt"}
keywords = ["cocotb", "HDL", "Hardware", "verification", "VHDL", "Verilog", "simulation", "EDA", "FPGA"]
authors = [
  {email = "kammoh@gmail.com"},
  {name = "Kamyar Mohajerani"}
]
# maintainers = []
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
dynamic = ["version", "description"]

dependencies = [
  "cocotb~=1.6",
  "attrs>=21",
  # the following deps should become optional:
  "python-box>=6",
  "cffi>=1.14",
]

[project.optional-dependencies]
test = [
  "pytest > 7",
  "pytest-cov[all]"
]

[project.urls]
# homepage = "example.com"
# documentation = "readthedocs.org"
# repository = "github.com"
# changelog = "github.com/me/spam/blob/master/CHANGELOG.md"

# [project.scripts]
# [project.gui-scripts]
# [project.entry-points."cocolight-setup"]

[build-system]
# requires = ["setuptools >= 45", "wheel", "setuptools_scm[toml] >= 6.2"]
# build-backend = "setuptools.build_meta"
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.setuptools_scm]


[tool.pylint.messages_control]
max-line-length = 120
disable = [
  "line-too-long",
  "invalid-name",
  "too-few-public-methods",
  "unspecified-encoding",
  "missing-function-docstring",
  "too-many-instance-attributes",
  "too-many-statements",
  "too-many-branches",
  "too-many-locals",
  "too-many-arguments",
  "too-many-nested-blocks",
  # to be removed:
  "missing-module-docstring",
  "unused-argument",
  "fixme",
  "f-string-without-interpolation",
  "wrong-import-order",
  "missing-class-docstring",
  "no-self-argument",               # from pydantic validators (classmethod)
  "no-self-use",                    # from pydantic validators (classmethod)
]
[tool.pylint.similarities]
min-similarity-lines = 10

# Ignore comments when computing similarities.
ignore-comments = "yes"

# Ignore docstrings when computing similarities.
ignore-docstrings = "yes"

# Ignore imports when computing similarities.
ignore-imports = "no"

[tool.pylint.design]
max-returns = 8