[tool.poetry]
name = "run-logger"
version = "0.0.1"
description = ""
authors = ["Ethan Brooks <ethanabrooks@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19.2"
gql = "^2.0.0"
jsonlines = "^2.0.0"
PyYAML = "^5.4.1"
redis = "^3.5.3"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
ipdb = "^0.13.9"
ipython = "^7.25.0"
Sphinx = "^4.5.0"
myst-parser = "^0.17.0"
sphinx-book-theme = "^0.3.2"
sphinx-copybutton = "^0.5.0"
sphinx-autobuild = "^2021.3.14"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
