name: bioconvert

channels:
- bioconda
- conda-forge
- defaults
- r

dependencies:
- python=3.7
- bedtools
- biopython
- bioawk
- colorlog
- biopython
- numpy
- matplotlib
- pandas
- pyBigWig
- mawk
- scipy
- pysam
- pillow
- easydev
- plink
- pyyaml
- pillow
- singularity
- pigz
- dsrc
- sambamba
- seqtk
- seqkit
- wiggletools
- graphviz   # provides dot for RTD
- ucsc-wigtobigwig
- ucsc-twobittofa
- ucsc-fatotwobit
- ucsc-bigwigtobedgraph
