name: CI
on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]
  workflow_dispatch:

jobs:
  tox:
    runs-on: ubuntu-latest
    env:
      GHDL_PLUGIN_MODULE: ghdl

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - run: sudo apt update -qq

      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - uses: docker://gcr.io/hdl-containers/impl

      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip tox tox-gh-actions

      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: "python -m tox"
