[tool.poetry]
name = "asyncops"
version = "0.1.0"
description = "The library for async operations."
authors = ["Zeb Taylor <zceboys@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
contextvars = "^2.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
