# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-02 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iati', '0007_auto_20170120_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='linked_data_uri',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitypolicymarker',
            name='alt_policy_marker',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider_organisation_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
