
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-13T15:14:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3fd58e0bb1785994ecaa5444850ab33154b71fab",
 "version": "0.0.73.post0.dev120"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
