[tool.poetry]
name = "nlhappy"
version = "0.1.52"
description = "致力于SOTA的中文自然语言处理库"
authors = ["wangmengdi <790990241@qq.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pytorch-lightning = "^1.5.10"
datasets = "^2.0.0"
spacy = "^3.2.3"
transformers = "^4.17.0"
hydra-core = "^1.1.1"
hydra-colorlog = "^1.1.0"
oss2 = "^2.15.0"
rich = "^12.0.0"
catalogue = "^2.0.7"
onnx = "^1.11.0"
onnxruntime = "^1.10.0"
wandb = "^0.12.11"

[tool.poetry.dev-dependencies]

[tool.poetry.plugins."spacy_factories"]
"span_classifier" = "nlhappy.spacy_components:make_spancat"

[tool.poetry.scripts]
nlhappy = "nlhappy.run:train"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# 添加清华镜像
[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true
