from .auth import ToyotaOneAuth as ToyotaOneAuth
from .client import ToyotaOneClient as ToyotaOneClient

def configure_logger() -> None: ...
def main(): ...
def save_tokens(tokens, auth_file) -> None: ...
def save_device_id(device_id, device_id_file) -> None: ...
def run_async(future): ...
