[package]
name = "ffzf"
version = "0.2.6"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ffzf"
crate-type = ["cdylib"]

[dependencies]
float-cmp = "0.9.0"
pyo3 = { version = "0.15.1", features = ["extension-module"] }
rayon = "1.5.1"
ordered-float = "2.10.0"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"