[tool.poetry]
name = "lung-annotator"
version = "0.1.0"
description = ""
authors = ["Mahyar Osanlouy <m.osanlouy@auckland.ac.nz>"]

packages = [
    { include = "lung-annotator" },
    { include = "lung-annotator/train.py" },
    { include = "lung-annotator/predict.py" },
    { include = "lung-annotator/predict.py" },
    { include = "lung-annotator/show.py" },
    { include = "lung-annotator/core/model.py" },
    { include = "lung-annotator/core/dataset.py" },
    { include = "lung-annotator/utils/show3d.py" },
    { include = "lung-annotator/utils/transform.py" },
]

[tool.poetry.dependencies]
python = "^3.9"
matplotlib = "*"
numpy = "1.22.3"
pytorch-lightning = "1.2.10"
scikit-learn = "0.24.2"
torchaudio = "0.9.0"
torchmetrics = "0.2.0"
tqdm = "4.49.0"
datasets = "1.6.2"
scipy = "1.6.1"
tensorboard = "2.8.0"
tensorboard-data-server = "0.6.1"
tensorboard-plugin-wit = "1.8.1"
torch = "1.9.0"
torchvision = "0.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
