[tool.poetry]
name = "plagdef"
version = "1.4.9"
description = "A tool which makes life hard for students who try to make theirs simple."
authors = ["Yannik Queisler"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/devWhyqueue/plagdef"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent"
]
exclude = ["*/tests"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
beautifulsoup4 = "^4.10"
click = "^8.0"
deep-translator = "^1.7"
jsonpickle = "^2.1"
langdetect = "^1.0"
networkx = "^2.7"
numpy = "^1.22"
pdfplumber = "^0.6"
ocrmypdf = "^13.4"
pyside6 = "^=6.2"
python-magic = "^0.4"
sortedcontainers = "^2.4"
stanza = "^1.3"
tqdm = "^4.63"
urlextract = "^1.5"
Werkzeug = "^2.0"

[tool.poetry.dev-dependencies]
coverage = "^6.3"
flake8 = "^4.0"
fpdf2 = "^2.5"
pytest = "^7.0"
tox = "^3.24"
tox-gh-actions = "^2.9"

[tool.poetry.scripts]
plagdef = "plagdef.app:cli"
plagdef-gui = "plagdef.app:gui"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py39, py310

[gh-actions]
python =
    3.9: py39
    3.10: py310

[testenv:py39]
whitelist_externals = make
commands = make coverage-ci

[testenv:py310]
whitelist_externals = make
commands = make test-ci
"""

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
