[tool.poetry]
name = "mvadkert-knife"
version = "0.1.0"
description = "Swiss army knife with various useful utilities."
authors = ["Miroslav Vadkerti <mvadkert@redhat.com>"]
license = "Apache-2.0"

packages = [
    { include = "knife" }
]

[tool.poetry.scripts]
knife = "knife:app"

[tool.poetry.dependencies]
python = "^3.7"
typer = "^0.4.1"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
